name       : python-referencing
version    : 0.30.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/r/referencing/referencing-0.30.2.tar.gz : 794ad8003c65938edcdbc027f1933215e0d0ccc0291e3ce20a4d87432b59efc0
homepage   : https://github.com/python-jsonschema/referencing
license    : MIT
component  : programming.python
summary    : JSON Referencing + Python
description: |
    An implementation-agnostic implementation of JSON reference resolution.
builddeps  :
    - python-build
    - python-hatch-vcs
    - python-installer
rundeps    :
    - python-attrs
    - python-rpds-py
build      : |
    %python3_setup
install    : |
    %python3_install
