name       : uhttpmock
version    : 0.9.0
release    : 7
source     :
    - https://gitlab.freedesktop.org/pwithnall/uhttpmock/-/archive/0.9.0/uhttpmock-0.9.0.tar.gz : 9fbcdcbc3e4b1ccde2281e3010f169036862423c936ffc8904ab30daad474b07
license    : LGPL-2.1-or-later
component  : programming.tools
homepage   : https://gitlab.freedesktop.org/pwithnall/uhttpmock
summary    : HTTP web service mocking project for projects which use libsoup
description: |
    HTTP web service mocking project for projects which use libsoup
builddeps  :
    - pkgconfig(libsoup-3.0)
    - gtk-doc
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
