# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : verilator
version    : '5.046'
release    : 54
source     :
    - https://github.com/verilator/verilator/archive/refs/tags/v5.046.tar.gz : 002bc6d92b203eb8b4612e1d198d8108517d4ec9859e131ef328015352fe6d0c
license    :
    - Artistic-2.0
    - LGPL-3.0-only
homepage   : https://www.veripool.org/wiki/verilator
component  : programming.tools
summary    : Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code.
description: |
    Verilator converts synthesizable (generally not behavioral) Verilog code into C++ or SystemC code. It is not a complete simulator, just a translator.
builddeps  :
    - help2man
rundeps    :
    - ccache
checkdeps  :
    - python-distro
setup      : |
    autoconf
    %configure
build      : |
    %make
install    : |
    %make_install
    %install_license LICENSE LICENSES/*
check      : |
    make test
