# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : breeze-gtk-theme
version    : 6.6.1
release    : 139
source     :
    - https://download.kde.org/stable/plasma/6.6.1/breeze-gtk-6.6.1.tar.xz : 570ff8f93babaf76f2192e6d0b15d5785b822155c26f426b840503ac2f393a03
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : desktop.theme
summary    : A GTK Theme Built to Match KDE's Breeze
description: |
    A GTK Theme Built to Match KDE's Breeze
builddeps  :
    - pkgconfig(Qt6Core)
    - breeze-devel
    - extra-cmake-modules
    - python-cairo
    - sassc
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
