name       : fwupd
version    : 1.9.6
release    : 5
source     :
    - https://github.com/fwupd/fwupd/releases/download/1.9.6/fwupd-1.9.6.tar.xz : c5fe96634bf6c5af7641cd08a48c6348aadd32d5f09ff8491e633f3c3a6bc0a1
license    : LGPL-2.1-or-later
homepage   : https://fwupd.org/
component  : system.utils
summary    : A simple daemon to allow session software to update firmware
description: |
    This project aims to make updating firmware on Linux automatic, safe and reliable.
    Additional information is available at the website: https://fwupd.org/
optimize   :
    - no-symbolic
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(efivar)
    - pkgconfig(flashrom)
    - pkgconfig(fwupd-efi)
    - pkgconfig(gi-docgen)
    - pkgconfig(gnutls)
    - pkgconfig(gusb)
    - pkgconfig(jcat)
    - pkgconfig(libarchive)
    - pkgconfig(libelf)
    - pkgconfig(libftdi1)
    - pkgconfig(libgcab-1.0)
    - pkgconfig(libpci)
    - pkgconfig(libprotobuf-c)
    - pkgconfig(libsmbios_c)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libudev)
    - pkgconfig(mbim-glib)
    - pkgconfig(mm-glib)
    - pkgconfig(pango)
    - pkgconfig(qmi-glib)
    - pkgconfig(sqlite3)
    - pkgconfig(tss2-esys)
    - pkgconfig(umockdev-1.0)
    - pkgconfig(valgrind)
    - pkgconfig(xmlb)
    - bubblewrap
    - font-noto-cjk
    - fwupd-efi
    - git
    - help2man
    - noto-sans-ttf
    - python3-cairo
    - python-gobject
    - python-pillow
    - shared-mime-info
    - vala
setup      : |
    %apply_patches
    %meson_configure \
        -D bluez=enabled \
        -D lzma=enabled \
        -D plugin_modem_manager=enabled \
        -D plugin_flashrom=enabled \
        -D efi_binary=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
