name       : gnote
version    : '45.0'
release    : 26
source     :
    - https://download.gnome.org/sources/gnote/45/gnote-45.0.tar.xz : 5d16fd87d140ec72fbb357b0569daefb8228e07814701546e6bde6572193c24a
homepage   : https://wiki.gnome.org/Apps/Gnote
license    : GPL-3.0-or-later
component  : office.notes
summary    : A simple and easy to use desktop note-taking application
description: |
    Gnote is a simple note-taking application for GNOME desktop environment. It allows you to capture your ideas, link them together using WikiWiki-style links, group together in notebooks and some extra features for everyday use. 
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-4.0)
    - pkgconfig(glibmm-2.68)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
