name       : poppler
version    : 23.10.0
release    : 46
source     :
    - https://poppler.freedesktop.org/poppler-23.10.0.tar.xz : 31a3dfdea79f4922402d313737415a44d44dc14d6b317f959a77c5bba0647dd9
    - git|https://gitlab.freedesktop.org/poppler/test.git : e3cdc82782941a8d7b8112f83b4a81b3d334601a
license    : GPL-2.0-or-later
component  :
    - desktop.library
    - qt5 : desktop.library
    - utils : office
homepage   : http://poppler.freedesktop.org/
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - qt6-devel :
        - /usr/include/poppler/qt6/
        - /usr/lib64/lib*qt6*.so
        - /usr/lib64/pkgconfig/*qt6*.pc
    - qt6 :
        - /usr/lib64/lib*qt6*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gpgme)
    - pkgconfig(poppler-data)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(nss)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt6Core)
    - libboost-devel
rundeps    :
    - poppler-data
    - devel :
        - poppler-utils
    - qt5-devel :
        - poppler-qt5
    - qt6-devel :
        - poppler-qt6
setup      : |
    %cmake -DTESTDATADIR=$sources/test.git \
           -DLIB_SUFFIX=%LIBSUFFIX% \
           -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
