# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-activities-stats
version    : 6.6.1
release    : 43
source     :
    - https://download.kde.org/stable/plasma/6.6.1/plasma-activities-stats-6.6.1.tar.xz : 00d114839521925577011630cc7ad8c6d5da315cc1498b92dfb45972b61d41b4
homepage   : https://invent.kde.org/plasma/plasma-activities-stats
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : A library for accessing the usage data collected by the activities system.
description: |
    A library for accessing the usage data collected by the activities system.
builddeps  :
    - pkgconfig(Qt6Core)
    - kf6-kconfig-devel
    - plasma-activities-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
