name       : python-notebook-shim
version    : 0.2.3
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/n/notebook_shim/notebook_shim-0.2.3.tar.gz : f69388ac283ae008cd506dda10d0288b09a017d822d5e8c7129a152cbd3ce7e9
homepage   : https://github.com/jupyter/notebook_shim
license    : BSD-3-Clause
component  : programming.python
summary    : A shim layer for notebook traits and config
description: |
    This project provides a way for JupyterLab and other frontends to switch to Jupyter Server for their Python Web application backend.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-jupyter-server
build      : |
    %python3_setup
install    : |
    %python3_install
