name       : libdex
version    : 0.4.0
release    : 2
source     :
    - https://download.gnome.org/sources/libdex/0.4/libdex-0.4.0.tar.xz : 36b027e8a368325be7214b987763b1a3794ed29fb7a938ba6ecd93a3be21c4fb
homepage   : https://gitlab.gnome.org/GNOME/libdex
license    : LGPL-2.1
component  : programming.library
summary    : A library supporting Deferred Execution
description: |
    A library supporting Deferred Execution
builddeps  :
    - pkgconfig(sysprof-capture-4)
    - gi-docgen
    - vala
patterns   :
    - docs :
        - /usr/share/doc/libdex-1
setup      : |
    %meson_configure -Dsysprof=true -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
