# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kdecoration
version    : 6.6.1
release    : 133
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kdecoration-6.6.1.tar.xz : 46b8749c09488d5ddc164b23747e266079092eef945d3002b344f07c31026e6f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
