# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ent
version    : 0.1.0
release    : 3
source     :
    - git|https://github.com/aerynOS/ent.git : f9b0380aec4c0bf46c629f522b46438e47a0b573
homepage   : https://github.com/aerynOS/ent
license    : MPL-2.0
component  : programming.utils
summary    : Tree management
description: |
    ent is a tool for working with packaging recipes in git trees/monorepos. Primarily it is intended for use with Serpent OS packaging, and to a limited degree, Solus packaging.
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build --no-default-features --features "ypkg"
install    : |
    %cargo_install
