# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xz
version    : 5.8.2
release    : 41
source     :
    - https://github.com/tukaani-project/xz/releases/download/v5.8.2/xz-5.8.2.tar.gz : ce09c50a5962786b83e5da389c90dd2c15ecd0980a258dd01f70f9e7ce58a8f1
homepage   : https://tukaani.org/xz/
license    :
    - 0BSD
    - GPL-2.0-or-later
component  : system.base
summary    : xz (Data compression software)
description: |
    XZ Utils is a free data compression software with high compression ratio. XZ Utils is the successor to LZMA.
optimize   :
    - lto
emul32     : true
setup      : |
    export CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
    %reconfigure --disable-rpath --disable-static
build      : |
    %make
install    : |
    %make_install
profile    : |
    %make check
check      : |
    %make check
patterns   :
    - docs :
        - /usr/share/doc
