name       : pangomm-2.48
version    : 2.50.1
release    : 1
source     :
    - https://gitlab.gnome.org/GNOME/pangomm/-/archive/2.50.1/pangomm-2.50.1.tar.gz : 6f09a57d7098ee82a55427be51c7870a9c627327262d0b8dcd9f836eb5f6498b
homepage   : https://gtkmm.org
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : C++ bindings to pango
description: |
    C++ bindings to pango
optimize   : speed
builddeps  :
    - pkgconfig(cairomm-1.16)
    - pkgconfig(glibmm-2.68)
    - pkgconfig(mm-common-util)
    - pkgconfig(pangocairo)
    - pkgconfig(sigc++-3.0)
    - doxygen
    - graphviz
patterns   :
    devel  : /usr/lib64/pangomm-2.48
setup      : |
    %meson_configure -Dmaintainer-mode=true
build      : |
    %ninja_build
install    : |
    %ninja_install
