name       : gnome-console
version    : 45.0
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-console/45/gnome-console-45.0.tar.xz : e7462128d2df2324a1d748062c40429cd0504af09e407067b33f3a9d0c59c8e1
homepage   : https://gitlab.gnome.org/GNOME/console
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A simple user-friendly terminal emulator for the GNOME desktop.
description: |
    A simple user-friendly terminal emulator for the GNOME desktop
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(vte-2.91-gtk4)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
