# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : yaml-cpp
version    : 0.9.0
release    : 6
source     :
    - https://github.com/jbeder/yaml-cpp/archive/refs/tags/yaml-cpp-0.9.0.tar.gz : 25cb043240f828a8c51beb830569634bc7ac603978e0f69d6b63558dadefd49a
homepage   : https://github.com/jbeder/yaml-cpp
license    : MIT
component  : programming.library
summary    : yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec
description: |
    yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
setup      : |
    %cmake_ninja -DYAML_BUILD_SHARED_LIBS=ON -DINSTALL_GTEST=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
