name       : adwaita-icon-theme
version    : '45.0'
release    : 26
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/45/adwaita-icon-theme-45.0.tar.xz : 2442bfb06f4e6cc95bf6e2682fdff98fa5eddc688751b9d6215c623cb4e42ff1
homepage   : https://gitlab.gnome.org/GNOME/adwaita-icon-theme
license    :
    - CC-BY-SA-3.0
    - LGPL-3.0-or-later
summary    : The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(librsvg-2.0)
    - inkscape
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 -i $pkgfiles/remove-unused-icon-theme-caches.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
