name       : libdisplay-info
version    : 0.1.1
release    : 1
source     :
    - https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive/0.1.1/libdisplay-info-0.1.1.tar.gz : a5aeef57817916286526292ec816a5338c4d3c0094ce91e584fc82b57070a44f
homepage   : https://gitlab.freedesktop.org/emersion/libdisplay-info
license    : MIT
component  : desktop.library
summary    : EDID and DisplayID library.
description: |
    EDID and DisplayID library.
builddeps  :
    - pkgconfig(hwdata)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
