# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : polkit-kde-agent
version    : 6.6.1
release    : 133
source     :
    - https://download.kde.org/stable/plasma/6.6.1/polkit-kde-agent-1-6.6.1.tar.xz : a03cd5b13077f9eb366364db9e4f6c0f82abe3d19053b5e64cde49e6a8e275fa
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Daemon providing a polkit authentication for KDE
description: |
    Daemon providing a polkit authentication for KDE.
builddeps  :
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(polkit-qt6-1)
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-knotifications-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
