# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : nvidia-vaapi-driver
version    : 0.0.16
release    : 20
homepage   : https://github.com/elFarto/nvidia-vaapi-driver
source     :
    - https://github.com/elFarto/nvidia-vaapi-driver/archive/refs/tags/v0.0.16.tar.gz : 799244cab5ace62b6354e429bd56faa83045470c438fbea13690b4d06754eb8b
license    : MIT
component  : xorg.display
summary    : A VA-API implemention using NVIDIA's NVDEC as the backend (UNSUPPORTED)
description: |
    This is an VA-API implementation that uses NVDEC as a backend. Mostly useful for firefox. (UNSUPPORTED)
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(ffnvcodec)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(libva)
    - nvidia-glx-driver-common
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
conflicts  :
    - libva-vdpau-driver
