# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xkeyboard-config
version    : '2.47'
release    : 18
source     :
    - https://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-2.47.tar.xz : e59984416a72d58b46a52bfec1b1361aa7d84354628227ee2783626c7a6db6b6
license    : MIT
component  : xorg.base
homepage   : https://www.x.org/
summary    : Keyboard configuration database
description: |
    The XKeyboardConfig package contains the keyboard configuration database for the X Window System.
builddeps  :
    - pkgconfig(x11)
setup      : |
    %meson_configure -Dxorg-rules-symlinks=true
build      : |
    %ninja_build
install    : |
    %ninja_install
