# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : feh
version    : 3.11.3
release    : 52
source     :
    - https://feh.finalrewind.org/feh-3.11.3.tar.bz2 : f2cca3592a433922c0db7a9365fd63e5402c121d932a9327e279c71be6501063
homepage   : https://feh.finalrewind.org/
license    : MIT
component  : multimedia.graphics
summary    : feh is an X11 image viewer aimed mostly at console users
description: |
    feh is an X11 image viewer aimed mostly at console users. Unlike most other viewers, it does not have a fancy GUI, but simply displays images. It is controlled via commandline arguments and configurable key/mouse actions.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(imlib2)
    - pkgconfig(libcurl)
    - pkgconfig(libexif)
    - pkgconfig(xinerama)
    - pkgconfig(xt)
build      : |
    %make PREFIX=/usr app=1 exif=1 inotify=1
install    : |
    %make_install PREFIX=/usr
    %install_license COPYING
    install -Dm00644 $pkgfiles/org.finalrewind.feh.feh.metainfo.xml -t $installdir/usr/share/metainfo
