name       : gnome-disk-utility
version    : '45.0'
release    : 35
source     :
    - https://download.gnome.org/sources/gnome-disk-utility/45/gnome-disk-utility-45.0.tar.xz : 3d8625faa99047bc4aefd29921ad728ab4d700cff86e0f2ec67e8dba877d0dd3
homepage   : https://wiki.gnome.org/Apps/Disks
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : GNOME Disks is a frontend for managing disks
description: |
    GNOME Disks provides libraries and applications for dealing with storage devices.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libhandy-1)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(pwquality)
    - pkgconfig(udisks2)
    - desktop-file-utils
    - docbook-xml
rundeps    :
    - cryptsetup
    - parted
setup      : |
    %patch -p1 -i $pkgfiles/0001-Install-to-usr-share-xdg-instead.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
