name       : gsettings-desktop-schemas
version    : '45.0'
release    : 58
source     :
    - https://download.gnome.org/sources/gsettings-desktop-schemas/45/gsettings-desktop-schemas-45.0.tar.xz : 365c8d04daf79b38c8b3dc9626349a024f9e4befdd31fede74b42f7a9fbe0ae2
homepage   : https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
description: |
    A collection of GSettings schemas for settings shared by various components of a GNOME Desktop.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 -i $pkgfiles/0001-Implement-Solus-defaults.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
