name       : python-jupyterlab
version    : 4.0.6
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyterlab/jupyterlab-4.0.6.tar.gz : 6c43ae5a6a1fd2fdfafcb3454004958bde6da76331abb44cffc6f9e436b19ba1
homepage   : https://github.com/jupyterlab/jupyterlab
license    : BSD-3-Clause
component  : programming.python
summary    : JupyterLab computational environment
description: |
    An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture. JupyterLab is the next-generation user interface for Project Jupyter offering all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible and powerful user interface. JupyterLab will eventually replace the classic Jupyter Notebook.
builddeps  :
    - python-build
    - python-hatch-jupyter-builder
    - python-installer
rundeps    :
    - python-async-lru
    - python-ipykernel
    - python-jupyter-lsp
    - python-jupyterlab-server
    - python-notebook-shim
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
