# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-openssl
version    : 25.3.0
release    : 22
source     :
    - https://pypi.debian.net/pyOpenSSL/pyopenssl-25.3.0.tar.gz : c981cb0a3fd84e8602d7afc209522773b94c1c2446a3c710a75b06fe1beae329
homepage   : https://pyopenssl.org/
license    : Apache-2.0
component  : programming.python
summary    : Python interface to the OpenSSL library
description: |
    pyOpenSSL - A Python wrapper around the OpenSSL library
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-cryptography
    - python-installer
    - python-setuptools
    - python-sphinx
checkdeps  :
    - python-pretend
    - python-pytest-rerunfailures
rundeps    :
    - python-cryptography
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test -v
