# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xcursorgen
version    : 1.0.9
release    : 6
source     :
    - https://www.x.org/releases/individual/app/xcursorgen-1.0.9.tar.xz : 0cc9e156ac84ca16ea902710af35e0faffa51d13797071e3b4b6cc7cbd493bbc
license    : MIT
component  : xorg.apps
homepage   : https://www.x.org/
summary    : Create an X cursor file from PNG images
description: |
    xcursorgen prepares X11 cursor sets for use with libXcursor.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(xcursor)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
