name       : python-jupyter-lsp
version    : 2.2.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter-lsp/jupyter-lsp-2.2.0.tar.gz : 8ebbcb533adb41e5d635eb8fe82956b0aafbf0fd443b6c4bfa906edeeb8635a1
homepage   : https://pypi.org/project/jupyter-lsp/
license    : BSD-3-Clause
component  : programming.python
summary    : Multi-Language Server WebSocket proxy for Jupyter Notebook/Lab server
description: |
    Multi-Language Server WebSocket proxy for Jupyter Notebook/Lab server
builddeps  :
    - python-build
    - python-installer
rundeps    :
    - python-jupyter-server
build      : |
    %python3_setup
install    : |
    %python3_install
