name       : python-gobject
version    : 3.46.0
release    : 31
source     :
    - https://download.gnome.org/sources/pygobject/3.46/pygobject-3.46.0.tar.xz : 426008b2dad548c9af1c7b03b59df0440fde5c33f38fb5406b103a43d653cafc
    - https://download.gnome.org/sources/pygobject/3.36/pygobject-3.36.1.tar.xz : d1bf42802d1cec113b5adaa0e7bf7f3745b44521dc2163588d276d5cd61d718f
homepage   : https://live.gnome.org/PyGObject
license    : LGPL-2.1-or-later
summary    : Python GObject bindings
description: |
    PyGObject provides Python bindings to the GObject class from GLib.
component  : programming.python
replaces   :
    - python3-gobject
    - devel : python3-gobject-devel
extract    : no
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(py3cairo)
    - pkgconfig(pycairo)
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
rundeps    :
    - python3-cairo
build      : |
    mkdir python2_legacy python3
    pushd python2_legacy
    tar xf $sources/pygobject-3.36*.tar.xz --strip-components=1
    python2.7 setup.py build $*
    popd
    pushd python3
    tar xf $sources/pygobject-$version.tar.xz --strip-components=1
    python3 setup.py build $*
    popd
install    : |
    pushd python2_legacy
    python2.7 setup.py install --root="%installroot%" $*
    popd
    pushd python3
    python3 setup.py install --root="%installroot%" $*
    popd
