name       : gnome-calculator
version    : 45.0.2
release    : 36
source     :
    - https://download.gnome.org/sources/gnome-calculator/45/gnome-calculator-45.0.2.tar.xz : 7dcbf32384897171cbe5483ec664d994e5e755e912ae1df911624f03c90867c2
homepage   : https://wiki.gnome.org/Apps/Calculator
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Calculator Application
description: |
    A tool for calculating mathematical equations. Uses standard mathematical notation where possible (so users do not have to learn the application when they already know maths). Easy enough to use for simple maths (add, subtract, multiply, divide). Powerful enough for mid-level mathematics (though not at the expense of being easy for simple mathematics).
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtksourceview-5)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libsoup-3.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
