# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : font-iosevka-ttf
version    : 34.1.0
release    : 88
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v34.1.0/PkgTTF-Iosevka-34.1.0.zip : f342be3b35eafeeef30c8c46e8ddac2b8b30eac7c9e65c11656a82242cb204a3
homepage   : https://typeof.net/Iosevka
license    : OFL-1.1
component  : desktop.font
summary    : Versatile typeface for code, from code.
description: |
    Iosevka is an open-source, sans-serif + slab-serif, monospace + quasi-proportional typeface family, designed for writing code, using in terminals, and preparing technical documents.
install    : |
    install -Dm00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
    install -Dm00644 $pkgfiles/iosevka.metainfo.xml $installdir/usr/share/metainfo/iosevka.metainfo.xml
