# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-desktop-branding
version    : 4.6.0
release    : 76
source     :
    # - https://github.com/getsolus/plasma-desktop-branding/releases/download/v4.6.0/plasma-desktop-branding-4.6.0.tar.xz : 929fe7738882541c5ac9b8f97753d900d711c1d6dc09975bde8be5a890209ae4
    - git|https://github.com/getsolus/plasma-desktop-branding.git : d0f464c669aa892bc00e2a3a1136a4a40702629f
homepage   : https://github.com/getsolus/plasma-desktop-branding
license    :
    - Apache-2.0
    - LGPL-2.0-only # layout-template
    - CC-BY-SA-4.0 # Wallpaper
summary    : Defaults for the Plasma Desktop
component  :
    - desktop.kde.core
    - livecd : desktop.kde
description: |
    Plasma Desktop Experience Configuration. Wallpaper red-cherry-leaves by W.carter
rundeps    :
    - breeze-cursor-theme
    - breeze-gtk-theme
    - breeze-light-cursor-theme
    - font-noto-emoji
    - noto-sans-ttf
    - noto-serif-ttf
    - solus-artwork-plasma
patterns   :
    - livecd :
        - /usr/lib/tmpfiles.d/plasma-desktop-branding.conf
        - /usr/share/livecd/kscreenlockerrc
        - /usr/share/sddm/sddm.conf.d/99_plasma_livecd.conf
        - /usr/share/glib-2.0/schemas/50_plasma_livecd.gschema.override
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
