name       : gnome-system-monitor
version    : 45.0.2
release    : 27
source     :
    - https://download.gnome.org/sources/gnome-system-monitor/45/gnome-system-monitor-45.0.2.tar.xz : c5e272d90bf9986a3f8613d76e0d27fa42dfacee5c0192e73921bb94b1868a2e
homepage   : https://wiki.gnome.org/Apps/SystemMonitor
license    : GPL-2.0-only
component  : desktop.gnome
summary    : A system monitor GUI application for GNOME
description: |
    A system monitor GUI application for GNOME
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwnck-3.0)
    - itstool
setup      : |
    %meson_configure -Dwnck=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/share/applications/gnome-system-monitor-kde.desktop
