name       : libgtkmm-3
version    : 3.24.8
release    : 21
source     :
    - https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.8.tar.xz : d2940c64922e5b958554b23d4c41d1839ea9e43e0d2e5b3819cfb46824a098c4
homepage   : https://gtkmm.org
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangomm-1.4)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
