name       : python-notebook
version    : 7.0.4
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/n/notebook/notebook-7.0.4.tar.gz : 0c1b458f72ce8774445c8ef9ed2492bd0b9ce9605ac996e2b066114f69795e71
homepage   : https://github.com/jupyter/notebook
license    : BSD-3-Clause
component  : programming.python
summary    : A web-based notebook environment for interactive computing
description: |
    The Jupyter Notebook is a web application that allows you to create and share documents that contain live code, equations, visualizations, and explanatory text. The Notebook has support for multiple programming languages, sharing, and interactive widgets.
builddeps  :
    - python-build
    - python-hatch-jupyter-builder
    - python-installer
    - python-jupyterlab
rundeps    :
    - python-jupyterlab
    - python-nbclassic
build      : |
    python3 -m build --wheel --no-isolation --skip-dependency-check
install    : |
    %python3_install
