name       : xdg-desktop-portal-gnome
version    : '45.0'
release    : 4
source     :
    - https://download.gnome.org/sources/xdg-desktop-portal-gnome/45/xdg-desktop-portal-gnome-45.0.tar.xz : 949598861c80000febf18cc12b3721c95c1bb1d19371fc2156dc4f33def5aff0
homepage   : https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
description: |
    A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(xdg-desktop-portal)
    - gnome-keyring
rundeps    :
    - xdg-desktop-portal-gtk
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
