name       : dav1d
version    : 1.3.0
release    : 25
source     :
    - https://code.videolan.org/videolan/dav1d/-/archive/1.3.0/dav1d-1.3.0.tar.bz2 : bde8db3d0583a4f3733bb5a4ac525556ffd03ab7dcd8a6e7c091bee28d9466b1
    - https://code.videolan.org/videolan/dav1d-test-data/-/archive/1.3.0/dav1d-test-data-1.3.0.tar.gz#dav1d-test-data.tar.gz : b383ae92f47894272b4ef5a4717419a3e951b0012d867c26958594cc69f7393c
homepage   : https://code.videolan.org/videolan/dav1d
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : AV1 decoder targeted to be small and fast
description: |
    dav1d is a new AV1 cross-platform Decoder, open-source, and focused on speed and correctness.
avx2       : yes
builddeps  :
    - pkgconfig(libxxhash)
setup      : |
    mkdir tests/dav1d-test-data
    tar -xf $sources/dav1d-test-data.tar.gz --strip-components=1  -C tests/dav1d-test-data
    %meson_configure \
                     --buildtype=release \
                     -Dtestdata_tests=true
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
