name       : python-jupyter_client
version    : 8.4.0
release    : 19
source     :
    - https://github.com/jupyter/jupyter_client/releases/download/v8.4.0/jupyter_client-8.4.0.tar.gz : dc1b857d5d7d76ac101766c6e9b646bf18742721126e72e5d484c75a993cada2
homepage   : https://github.com/jupyter/jupyter_client
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter protocol client APIs
description: |
    jupyter_client contains the reference implementation of the Jupyter protocol. It also provides client and kernel management APIs for working with kernels. It also provides the jupyter kernelspec entrypoint for installing kernelspecs for use with Jupyter frontends.
builddeps  :
    - openssh               # check
    - python-build
    - python-hatchling
    - python-installer
    - python-packaging
    - python-ipykernel      # check
    - python-msgpack        # check
    - python-psutil         # check
    - python-pytest-asyncio # check
    - python-pytest-jupyter # check
    - python-pytest-timeout # check
rundeps    :
    - python-dateutil
    - python-jupyter_core
    - python-pyzmq
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # https://github.com/jupyter/jupyter_client/issues/979
    %python3_test pytest -v \
            --deselect tests/test_kernelmanager.py \
            --deselect tests/test_kernelspecapp.py::test_kernelspec_app \
            --deselect tests/test_localinterfaces.py::test_load_ips
