# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : swaybg
version    : 1.2.2
release    : 6
source     :
    - https://github.com/swaywm/swaybg/archive/refs/tags/v1.2.2.tar.gz : 94e5c06a765d969e554b0f321f9cdf9c283a3fdaf70ad4e3d28163b21bd4d240
license    : MIT
homepage   : https://github.com/swaywm/swaybg
component  : desktop
summary    : Wallpaper utility for Wayland compositors
description: |
    Wallpaper utility for Wayland compositors
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
