name       : python-orjson
version    : 3.9.8
release    : 31
source     :
    - https://files.pythonhosted.org/packages/source/o/orjson/orjson-3.9.8.tar.gz : ed1adc6db9841974170a5195b827ee4e392b1e8ca385b19fcdc3248489844059
license    :
    - Apache-2.0
    - MIT
homepage   : https://github.com/ijl/orjson
component  : programming.python
summary    : Fast, correct Python JSON library
description: |
    Fast, correct Python JSON library supporting dataclasses, datetimes, and numpy
clang      : yes
builddeps  :
    - cargo
    - numpy #check
    - python-arrow #check
    - python-installer
    - python-maturin
    - python-psutil #check
    - python-pytest #check
    - python-pytz #check
    - python-tomli
build      : |
    maturin build --release --strip --manylinux off
install    : |
    python3 -m installer --destdir=$installdir target/wheels/*.whl
check      : |
    %python3_test pytest3
