name       : python-jupyter-server
version    : 2.7.3
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter_server/jupyter_server-2.7.3.tar.gz : d4916c8581c4ebbc534cebdaa8eca2478d9f3bfdd88eae29fcab0120eac57649
homepage   : https://github.com/jupyter-server/jupyter_server
license    : BSD-3-Clause
component  : programming.python
summary    : The backend—i.e. core services, APIs, and REST endpoints—to Jupyter web applications
description: |
    The Jupyter Server provides the backend (i.e. the core services, APIs, and REST endpoints) for Jupyter web applications like Jupyter notebook, JupyterLab, and Voila.
builddeps  :
    - python-build
    - python-hatch-jupyter-builder
    - python-installer
rundeps    :
    - python-anyio
    - python-argon2-cffi
    - python-jupyter_client
    - python-jupyter-events
    - python-jupyter-server-terminals
    - python-nbconvert
    - python-overrides
    - python-prometheus_client
    - python-send2trash
    - python-websocket-client
build      : |
    %python3_setup
install    : |
    %python3_install
