name       : gnome-latex
version    : 3.46.0
release    : 20
source     :
    - https://download.gnome.org/sources/gnome-latex/3.46/gnome-latex-3.46.0.tar.xz : d67555639b2a15a8aebd54f335354e44fe3433143ae3cb3cca7a8e26f8112ada
homepage   : https://gitlab.gnome.org/swilmet/gnome-latex
license    : GPL-3.0-or-later
component  : editor
summary    : LaTeXila is an Integrated LaTeX Environment for the GNOME desktop
description: |
    LaTeXila is an Integrated LaTeX Environment for the GNOME desktop
replaces   :
    - latexila
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gspell-1)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(tepl-6)
    - itstool
    - vala
    - yelp-tools
rundeps    :
    - texlive
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
