# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kwayland
version    : 6.6.1
release    : 118
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kwayland-6.6.1.tar.xz : cc26e022a3090babacd0ae8ec146d1bd42df91eb8cb76a407b072e9cdd836017
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
component  : programming.library
summary    : Qt-style API to interact with wayland
description: |
    KWayland is a Qt-style API to interact with the wayland-client and wayland-server API.
builddeps  :
    - pkgconfig(Qt6Designer)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(x11)
    - pkgconfig(xkbcommon)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt6-base-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
