# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : fastfetch
version    : 2.59.0
release    : 68
source     :
    - https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.59.0.tar.gz : 978e2524d0dc1ff9fd8c89fb24ae5b131af18ff108da82c6d99823712557e499
homepage   : https://github.com/fastfetch-cli/fastfetch
license    : MIT
component  : system.utils
summary    : Like neofetch, but much faster because written in C
description: |
    Fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written in pure c, with performance and customizability in mind.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(OpenCL)
    - pkgconfig(dconf)
    - pkgconfig(ddcutil)
    - pkgconfig(egl)
    - pkgconfig(gio-2.0)
    - pkgconfig(libdrm)
    - pkgconfig(libelf)
    - pkgconfig(libpci)
    - pkgconfig(libpulse)
    - pkgconfig(libxfconf-0)
    - pkgconfig(sqlite3)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(xrandr)
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DENABLE_IMAGEMAGICK6='OFF' \
        -DENABLE_RPM='OFF' \
        -Wno-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
