name       : libgweather
version    : 4.4.0
release    : 33
source     :
    - https://download.gnome.org/sources/libgweather/4.4/libgweather-4.4.0.tar.xz : 366e866ff2a708b894cfea9475b8e8ff54cb3e2b477ea72a8ade0dabee5f48a4
homepage   : https://wiki.gnome.org/Projects/LibGWeather
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : The libgweather package is a library used to access weather information from online services for numerous locations
description: |
    The libgweather package is a library used to access weather information from online services for numerous locations.
builddeps  :
    - pkgconfig(geocode-glib-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(pygobject-3.0)
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=false -Denable_vala=true -Dsoup2=false
build      : |
    %ninja_build
install    : |
    %ninja_install
