name       : python-ipykernel
version    : 6.25.2
release    : 20
source     :
    - https://files.pythonhosted.org/packages/source/i/ipykernel/ipykernel-6.25.2.tar.gz : f468ddd1f17acb48c8ce67fcfa49ba6d46d4f9ac0438c1f441be7c3d1372230b
homepage   : https://github.com/ipython/ipykernel
license    : BSD-3-Clause
component  : programming.python
summary    : IPython Kernel for Jupyter
description: |
    IPython Kernel for Jupyter.
builddeps  :
    - matplotlib            # check
    - python-build
    - python-comm           # check
    - python-debugpy        # check
    - python-hatchling
    - python-installer
    - python-flaky          # check
    - python-ipyparallel    # check
    - python-jupyter_client
    - python-nest-asyncio
    - python-pytest-asyncio # check
    - python-pytest-timeout # check
    - python-trio           # check
rundeps    :
    - python-comm
    - python-debugpy
    - python-jupyter_client
    - python-nest-asyncio
    - python3-ipython
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
