name       : tecla
version    : 45.0
release    : 1
source     :
    - https://download.gnome.org/sources/tecla/45/tecla-45.0.tar.xz : 5c02bb4019b1cffb5663da6107503eff853836a8783dd4705dd04a49f7adc25b
homepage   : https://gitlab.gnome.org/GNOME/tecla
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Keyboard layout viewer
description: |
     Keyboard layout viewer
builddeps  :
    - pkgconfig(libadwaita-1)
    - pkgconfig(xkbregistry)
    - pkgconfig(wayland-egl)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
