name       : geary
version    : '44.1'
release    : 41
source     :
    - https://download.gnome.org/sources/geary/44/geary-44.1.tar.xz : 7d11cb6e1c504e108c2dc91aa2256a4404dcabe7d1c873d8d6094e2df335a277
homepage   : https://wiki.gnome.org/Apps/Geary
license    :
    - BSD-2-Clause # Snowball
    - CC-BY-SA-3.0 # Icons
    - LGPL-2.1-or-later # Source
summary    : Geary is a mail client for GNOME
description: |
    Geary is a mail client for GNOME
component  : network.mail
clang      : no
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(enchant-2)
    - pkgconfig(folks)
    - pkgconfig(gcr-3)
    - pkgconfig(gee-0.8)
    - pkgconfig(gmime-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(gsound)
    - pkgconfig(gspell-1)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libunwind)
    - pkgconfig(libytnef)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.1)
    - desktop-file-utils
    - itstool
    - libstemmer-devel
    - valadoc
setup      : |
    %meson_configure -Dprofile=release
build      : |
    %ninja_build
install    : |
    %ninja_install
