# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : chafa
version    : 1.18.1
release    : 1
source     :
    - https://github.com/hpjansson/chafa/archive/refs/tags/1.18.1.tar.gz : 2f7c82fc144d2ddfed9ee863bbbb201953c2e4e0cc97e541fde25171cab7b826
homepage   : https://hpjansson.org/chafa/
license    :
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : system.utils
summary    : Image-to-text converter for terminal display
description: |
    Chafa is a command-line utility that converts image data, including animated GIFs,
    into graphics formats or ANSI/Unicode character art suitable for display in a
    terminal. It supports a wide range of symbols and palettes, transparency,
    animations, and many image formats (JPEG, PNG, WebP, SVG, TIFF, AVIF, HEIF, JPEG XL).
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glib-2.0)
    - pkgconfig(libavif)
    - pkgconfig(libheif)
    - pkgconfig(libjpeg)
    - pkgconfig(libjxl)
    - pkgconfig(libjxl_threads)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(libwebpdemux)
    - docbook-xml
setup      : |
    %autogen --disable-static --enable-man
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING*

    # Install completions
    install -Dm00644 tools/completions/bash-completion.sh $installdir/usr/share/bash-completion/completions/chafa
    install -Dm00644 tools/completions/zsh-completion.zsh $installdir/usr/share/zsh/site-functions/_chafa
    install -Dm00644 tools/completions/fish-completion.fish $installdir/usr/share/fish/vendor_completions.d/chafa.fish
patterns   :
    - devel :
        - /usr/lib64/chafa/include/chafaconfig.h
