# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kde-gtk-config
version    : 6.6.1
release    : 134
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kde-gtk-config-6.6.1.tar.xz : 9a23290a4ecc56ad7aec0777e6ad2540d02d674e65194b582344fc8ab722bf87
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
builddeps  :
    - pkgconfig(KF6GuiAddons)
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(Qt6Svg)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - gsettings-desktop-schemas
    - kdecoration-devel
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kiconthemes-devel
    - sassc
    - xsettingsd
rundeps    :
    - gsettings-desktop-schemas
    - xsettingsd
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
