name       : python-overrides
version    : 7.4.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/o/overrides/overrides-7.4.0.tar.gz : 9502a3cca51f4fac40b5feca985b6703a5c1f6ad815588a7ca9e285b9dca6757
homepage   : https://github.com/mkorpela/overrides
license    : Apache-2.0
component  : programming.python
summary    : A decorator to automatically detect mismatch when overriding a method
description: |
    A decorator @override that verifies that a method that should override an inherited method actually does it.
builddeps  :
    - python-build
    - python-installer
    - python-pytest    # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
