name       : cairomm
version    : 1.14.5
release    : 19
source     :
    - https://www.cairographics.org/releases/cairomm-1.14.5.tar.xz : 70136203540c884e89ce1c9edfb6369b9953937f6cd596d97c78c9758a5d48db
homepage   : https://www.cairographics.org/cairomm/
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : C++ bindings to Cairo
description: |
    C++ bindings to Cairo
replaces   :
    - libcairomm
    - devel : libcairomm-devel
    - docs : libcairomm-docs
optimize   : speed
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(glibmm-2.4)
    - doxygen
    - graphviz
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel :
        - /usr/lib64/cairomm-1.0/include
setup      : |
    %meson_configure -Dbuild-documentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install
