name       : gjs
version    : 1.78.0
release    : 54
source     :
    - https://download.gnome.org/sources/gjs/1.78/gjs-1.78.0.tar.xz : fbaa20e0917668830800f92951688f9fc08f01296affd5cdb4b35f750be27dc9
component  : desktop.gnome.core
homepage   : https://wiki.gnome.org/action/show/Projects/Gjs
license    : GPL-2.0-or-later
summary    : GNOME JavaScript bindings
description: |
    GNOME JavaScript bindings
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(mozjs-115)
rundeps    :
    - mozjs
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
