name       : libvirt-python
version    : 9.8.0
release    : 42
source     :
    - https://libvirt.org/sources/python/libvirt-python-9.8.0.tar.gz : 4069ecb226eab1b810728ef62a9c993a592b2258b0ff489937addd560020a5f1
license    : LGPL-2.1-or-later
homepage   : https://libvirt.org/
component  : programming.python
summary    : The libvirt virtualization API python binding
description: |
    The libvirt-python package provides a module that permits applications written in the Python programming language to call the interface supplied by the libvirt library, to manage the virtualization capabilities of recent versions of Linux.
builddeps  :
    - pkgconfig(libvirt)
    - pkgconfig(python3)
    - python-lxml
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
