name       : mandown
version    : 0.1.3
release    : 1
source     :
    - https://gitlab.com/kornelski/mandown/-/archive/0.1.3/mandown-0.1.3.tar.bz2 : da4cf444385a2595e126977e574d67c800b1083c8731a7747be4b8ee116775e4
homepage   : https://gitlab.com/kornelski/mandown
license    : Apache-2.0
component  : programming.tools
summary    : Create man pages from Markdown markup
description: |
    Create man pages from markdown markup.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release --all-features
install    : |
    install -Dm00755 target/release/mandown $installdir/usr/bin/mandown
