# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : thermald
version    : 2.5.11
release    : 19
source     :
    - https://github.com/intel/thermal_daemon/archive/refs/tags/v2.5.11.tar.gz : 0f4d7371d2cadf12f868e4b56d0e70af07a1c3b7d883dbe541a3707e449ea1ad
license    : GPL-2.0-or-later
homepage   : https://github.com/intel/thermal_daemon
component  : system.utils
summary    : Thermal daemon for IA
description: |
    Thermal daemon for IA
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(libxml-2.0)
    - pkgconfig(upower-glib)
    - autoconf-archive
    - gtk-doc
setup      : |
    %autogen --with-dbus-sys-dir=/usr/share/dbus-1/system.d/
build      : |
    %make
install    : |
    %make_install

    # Users may systemctl mask to turn it off.
    install -d -D -m 00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv thermald.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.thermald.service
    ln -sv ../thermald.service $installdir/%libdir%/systemd/system/multi-user.target.wants
