name       : python-jupyter-events
version    : 0.7.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter_events/jupyter_events-0.7.0.tar.gz : 7be27f54b8388c03eefea123a4f79247c5b9381c49fb1cd48615ee191eb12615
homepage   : https://github.com/jupyter/jupyter_events/
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Event System library
description: |
    Jupyter Events enables Jupyter Python Applications (e.g. Jupyter Server, JupyterLab Server, JupyterHub, etc.) to emit events—structured data describing things happening inside the application. Other software (e.g. client applications like JupyterLab) can listen and respond to these events.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-json-logger
    - python-jsonschema
    - python-rfc3339-validator
    - python-rfc3986-validator
    - python-traitlets
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
