name       : glibmm-2.68
version    : 2.78.0
release    : 6
source     :
    - https://download.gnome.org/sources/glibmm/2.78/glibmm-2.78.0.tar.xz : 5d2e872564996f02a06d8bbac3677e7c394af8b00dd1526aebd47af842a3ef50
homepage   : https://gtkmm.org
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GLib (2.68 ABI)
description: |
    C++ bindings to GLib (2.68 ABI)
builddeps  :
    - pkgconfig(sigc++-3.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
