name       : libportal
version    : 0.7.1
release    : 7
source     :
    - https://github.com/flatpak/libportal/releases/download/0.7.1/libportal-0.7.1.tar.xz : 297b90b263fad22190a26b8c7e8ea938fe6b18fb936265e588927179920d3805
homepage   : https://github.com/flatpak/libportal
license    : GPL-2.0-or-later
component  : desktop.library
summary    : libportal provides GIO-style async APIs for most Flatpak portals.
description: |
    libportal provides GIO-style async APIs for most Flatpak portals.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(Qt5X11Extras)
    - vala
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
