# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kwayland-integration
version    : 6.6.1
release    : 134
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kwayland-integration-6.6.1.tar.xz : b735645feb28fbc8d5f527046a90499e70a1b031aeb1a5be4c55a91975fc7f75
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Provides integration plugins for various KDE frameworks
description: |
    Provides integration plugins for various KDE frameworks.
builddeps  :
    - pkgconfig(KF5WaylandClient)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - kwindowsystem-devel
    - plasma-wayland-protocols-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
