# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : oxygen-sounds
version    : 6.6.1
release    : 41
source     :
    - https://download.kde.org/stable/plasma/6.6.1/oxygen-sounds-6.6.1.tar.xz : 439b1949e3477ea5ef976ef0ee1fe8a3ac133657a82ee6a8dcff5f260df452ca
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.theme
summary    : The Oxygen Sound Theme
description: The Oxygen Sound Theme
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
