name       : openmsx
version    : 19.1
release    : 11
source     :
    - https://github.com/openMSX/openMSX/archive/RELEASE_19_1.tar.gz : 06b204ed5e126be9af6a268717c911a9d67415745e02845f7d5657fbb89b38ee
license    : GPL-2.0-or-later
component  : games.emulator
summary    : openMSX is an emulator for the MSX home computer system
description: |
    openMSX is an emulator for the MSX home computer system
builddeps  :
    - pkgconfig(SDL2_ttf)
    - pkgconfig(alsa)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libpng)
    - pkgconfig(tcl)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
setup      : |
    sed -i 's@SYMLINK_FOR_BINARY:=true@SYMLINK_FOR_BINARY:=false@' build/custom.mk
    sed -i 's@INSTALL_BASE:=/opt/openMSX@INSTALL_BASE:=/usr/share/openmsx@' build/custom.mk
    echo 'INSTALL_DOC_DIR:=/usr/share/doc/openmsx' >> build/custom.mk
    echo 'INSTALL_SHARE_DIR:=/usr/share/openmsx' >> build/custom.mk
    echo 'INSTALL_BINARY_DIR:=/usr/bin' >> build/custom.mk

    %configure
build      : |
    %make
install    : |
    %make_install
