name       : python-llfuse
version    : 1.5.0
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/l/llfuse/llfuse-1.5.0.tar.gz : d094448bb4eb20099537be53dc2b5b2c0369d36bde09207a9bb228cc3cd58ee1
homepage   : https://github.com/python-llfuse/python-llfuse/
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python bindings for the low-level FUSE API
description: |
    Python-LLFUSE is a set of Python bindings for the low level FUSE API.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libattr)
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
