# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-nm
version    : 6.6.1
release    : 140
source     :
    - https://download.kde.org/stable/plasma/6.6.1/plasma-nm-6.6.1.tar.xz : 72291bd704da3c91ddeb58b434cb3130138ca1fb20eee4210e26318771e08457
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
libsplit   : false
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(mobile-broadband-provider-info)
    - pkgconfig(openconnect)
    - kf6-kcmutils-devel
    - kf6-kcolorscheme-devel
    - kf6-kdbusaddons-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-ksvg-devel
    - kf6-kwallet-devel
    - kf6-modemmanager-qt-devel
    - kf6-networkmanager-qt-devel
    - kf6-prison-devel
    - libplasma-devel
    - qca-qt6-devel
    - qcoro-qt6-devel
    - qt6-base-private-devel
rundeps    :
    - kf6-kirigami
    - kf6-prison
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSES/*
