# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : evtest
version    : '1.36'
release    : 2
source     :
    - https://gitlab.freedesktop.org/libevdev/evtest/-/archive/evtest-1.36/evtest-evtest-1.36.tar.gz : 3b9a66c92e48b0cd13b689530b5729c031bc1bcbfe9d19c258f9245e2f8d2a0f
homepage   : https://gitlab.freedesktop.org/libevdev/evtest
license    : GPL-2.0-or-later
component  : system.utils
summary    : Kernel input device debugging
description: |
    evtest is a tool to print evdev kernel events. It reads directly from the kernel device and prints a device description and the events with the value and the symbolic name.
builddeps  :
    - pkgconfig(libevdev)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
