# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kde-cli-tools
version    : 6.6.1
release    : 135
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kde-cli-tools-6.6.1.tar.xz : 28810d0b4407d0ac752f9420ecd843af2f5568751fc1c70d114620f0596fdeec
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Tools to better interact with the system
description: |
    Tools based on KDE Frameworks 6 to better interact with the system.
builddeps  :
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(Qt6Svg)
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kdesu-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kparts-devel
    - kf6-kservice-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc
