name       : gnome-boxes
version    : '45.0'
release    : 59
source     :
    - https://download.gnome.org/sources/gnome-boxes/45/gnome-boxes-45.0.tar.xz : cc63080eefa147a8472ab1a5ff087b97a27ab723a4ee005ed41e8c9dd7798e41
license    : GPL-2.0-only
homepage   : https://apps.gnome.org/app/org.gnome.Boxes/
component  : desktop.gnome
summary    : A simple GNOME 3 application to access remote or virtual systems.
description: |
    A simple GNOME 3 application to access remote or virtual systems
builddeps  :
    - pkgconfig(gtksourceview-4)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libarchive)
    - pkgconfig(libhandy-1)
    - pkgconfig(libosinfo-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libvirt-glib-1.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(spice-protocol)
    - pkgconfig(tracker-sparql-3.0)
    - pkgconfig(webkit2gtk-4.1)
    - pkgconfig(winpr2)
    - pkgconfig(vte-2.91)
    - desktop-file-utils
    - git
    - itstool
    - intltool
    - vala
patterns   :
    - /usr/share/man
rundeps    :
    - qemu
    - spice
    - virglrenderer
setup      : |
    %meson_configure -Ddistributor_name=Solus
build      : |
    %ninja_build
install    : |
    %ninja_install
