name       : libsecret
version    : 0.21.1
release    : 22
source     :
    - https://download.gnome.org/sources/libsecret/0.21/libsecret-0.21.1.tar.xz : 674f51323a5f74e4cb7e3277da68b5afddd333eca25bc9fd2d820a92972f90b1
homepage   : https://wiki.gnome.org/Projects/Libsecret
component  : desktop.gnome.core
license    : LGPL-2.1-or-later
summary    : The libsecret package contains a GObject based library for accessing the Secret Service API.
description: |
    The libsecret package contains a GObject based library for accessing the Secret Service API.
builddeps  :
    - pkgconfig(libgcrypt)
    - vala
setup      : |
    %meson_configure -Dmanpage=false -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
