name       : cargo-c
version    : 0.9.24
release    : 28
source     :
    - https://github.com/lu-zero/cargo-c/archive/refs/tags/v0.9.24.tar.gz : 32f2f5c802c01c51cf93471fcf876d0cc68edbc31d22005b9f07e4549d5b98b1
    - https://github.com/lu-zero/cargo-c/releases/download/v0.9.24/Cargo.lock : 59395514ce5df6b56beb7cb970874f9a65b801950a04090a875ce3770a0754d8
license    : MIT
component  : programming.tools
homepage   : https://crates.io/crates/cargo-c
summary    : Build and install C-compatible libraries
description: |
    Cargo applet to build and install C-ABI compatible dynamic and static libraries.
    It produces and installs a correct pkg-config file, a static library and a dynamic library, and a C header to be used by any C (and C-compatible) software.
builddeps  :
    - pkgconfig(libcurl)
    - cargo
rundeps    :
    - cargo
networking : yes
setup      : |
    cp $sources/Cargo.lock ./Cargo.lock
    cargo fetch --locked 
build      : |
    cargo build --frozen --release
install    : |
    cargo install \
        --locked \
        --no-track \
        --path . \
        --root=$installdir/usr
