# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-systemmonitor
version    : 6.6.1
release    : 74
source     :
    - https://download.kde.org/stable/plasma/6.6.1/plasma-systemmonitor-6.6.1.tar.xz : c5a84baf7fa9a368175865b7f5841ac8607239957cdd94b7c9e874894f45ec0d
homepage   : https://kde.org/plasma-desktop
license    : GPL-3.0-only
component  : desktop.kde.core
summary    : New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
description: |
    New version of KSysGuard built on top of the new KStats daemon and using QML for its UI
libsplit   : false
builddeps  :
    - kf6-kdbusaddons-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knewstuff-devel
    - kirigami-addons-devel
    - ksystemstats
    - libksysguard-devel
    - qt6-base-private-devel
rundeps    :
    - kf6-kiconthemes
    - kf6-kirigami
    - kirigami-addons
    - ksystemstats
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
