# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : drkonqi
version    : 6.6.1
release    : 131
source     :
    - https://download.kde.org/stable/plasma/6.6.1/drkonqi-6.6.1.tar.xz : 019befea19c6a8d31ff3adca886b9547b1c12553f3702a23d57b9b5fa41fd332
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Crash Handler
description: |
    The KDE Crash Handler.
networking : true
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(python3)
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kwallet-devel
    - kf6-syntax-highlighting-devel
    - polkit-qt-1-qt6-devel
    - python-distro
    - python-psutil
    - python-pygdbmi
    - python-sentry-sdk
rundeps    :
    - gdb
    - kf6-kcmutils
    - kf6-kirigami
    - kf6-kitemmodels
    - python-psutil
    - python-pygdbmi
    - python-sentry-sdk
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6 -DWITH_GDB12=ON \
               -DWITH_PYTHON_VENDORING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
