name       : libpng
version    : 1.6.40
release    : 24
source     :
    - https://kumisystems.dl.sourceforge.net/project/libpng/libpng16/1.6.40/libpng-1.6.40.tar.xz : 535b479b2467ff231a3ec6d92a525906fb8ef27978be4f66dbe05d3f3a01b3a1
homepage   : http://www.libpng.org/pub/png/
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
builddeps  :
    - pkgconfig32(zlib)
patterns   :
    - devel :
        - /usr/bin/libpng*-config
emul32     : yes
setup      : |
    %configure --disable-static --enable-intel-sse
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
check      : |
    %make check
