# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : layer-shell-qt
version    : 6.6.1
release    : 75
source     :
    - https://download.kde.org/stable/plasma/6.6.1/layer-shell-qt-6.6.1.tar.xz : 61a413c113ff808a4164a77c077b9d8432d6d99f809a308af001772e9b0f88a7
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt6WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - extra-cmake-modules
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
