# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : python-jaraco.text
version    : 4.2.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/j/jaraco_text/jaraco_text-4.2.0.tar.gz : 194e386aa5b15a6616019df87a6b29c00fd3c9c8b0475731b64633ca7afd495b
homepage   : https://github.com/jaraco/jaraco.text
license    : MIT
component  : programming.python
summary    : Provides handy routines for dealing with text.
description: |
    Provides handy routines for dealing with text, such as wrapping, substitution, trimming, stripping, prefix and suffix removal, line continuation, indentation, comment processing, identifier processing, values parsing, case insensitive comparison, and more.
builddeps  :
    - python-build
    - python-coherent-licensed
    - python-installer
    - python-setuptools-scm
rundeps    :
    - python-jaraco.context
    - python-jaraco.functools
    - python-more-itertools
    - python-typer
checkdeps  :
    - python-inflect
    - python-jaraco.context
    - python-jaraco.functools
    - python-more-itertools
    - python-pytest
    - python-typer
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
