name       : network-manager-applet
version    : 1.34.0
release    : 52
source     :
    - https://download.gnome.org/sources/network-manager-applet/1.34/network-manager-applet-1.34.0.tar.xz : ab368e470f6b161fc8b834bc97912b7e79af92b8cd7ea399c2d400ce89aba5a8
homepage   : https://gitlab.gnome.org/GNOME/network-manager-applet
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : NetworkManager Applet
description: |
    NetworkManager Applet
builddeps  :
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(jansson)
    - pkgconfig(libnma)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-unstable)
    - pkgconfig(mm-glib)
setup      : |
    %meson_configure --sysconfdir=/usr/share/ -Dselinux=false
build      : |
    %ninja_build
install    : |
    %ninja_install
