name       : exiv2
version    : 0.27.7
release    : 18
source     :
    - https://github.com/Exiv2/exiv2/archive/v0.27.7.tar.gz : 551b1266e3aabd321f6d555dccd776128ee449d5039feafee927a1f33f7a9753
license    : GPL-2.0-or-later
component  : desktop.library
homepage   : https://exiv2.org/
summary    : exif and iptc metadata manipulation library and tools
description: |
    Exiv2, a C++ library and a command line utility to read and write Exif, IPTC and XMP image metadata.
builddeps  :
    - pkgconfig(libcurl)
rundeps    :
    - devel :
        - curl-devel
setup      : |
    %cmake_ninja \
        -DEXIV2_ENABLE_BMFF=on \
        -DEXIV2_ENABLE_CURL=on \
        -DEXIV2_ENABLE_DYNAMIC_RUNTIME=off \
        -DEXIV2_ENABLE_NLS=on \
        -DEXIV2_ENABLE_VIDEO=on \
        -DEXIV2_ENABLE_WEBREADY=on .
build      : |
    %ninja_build
install    : |
    %ninja_install
# The security patch tooling can break with check steps. This can be re-enabled for testing locally
# check      : |
#     ninja tests %JOBS% -C solusBuildDir
