name       : libgtkmm-4
version    : 4.12.0
release    : 1
source     :
    - https://download.gnome.org/sources/gtkmm/4.12/gtkmm-4.12.0.tar.xz : fbc3e7618123345c0148ef71abb6548d421f52bb224fbda34875b677dc032c92
homepage   : https://gtkmm.org
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GTK+
description: |
    C++ bindings to GTK+
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(gtk4)
    - pkgconfig(pangomm-2.48)
patterns   :
    - devel : [/usr/lib64/g*]
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
