# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kdeplasma-addons
version    : 6.6.1
release    : 143
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kdeplasma-addons-6.6.1.tar.xz : cbead79f090df1ace14fe93cc30baf332a592dbcf8e260ef20f825c6c4bc277e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
libsplit   : false
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Quick3D)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(icu-i18n)
    - pkgconfig(x11)
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kdeclarative-devel
    - kf6-kglobalaccel-devel
    - kf6-kholidays-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-krunner-devel
    - kf6-ksvg-devel
    - kf6-kunitconversion-devel
    - kf6-kxmlgui-devel
    - kf6-networkmanager-qt-devel
    - kf6-purpose-devel
    - kf6-sonnet-devel
    - kirigami-addons-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma-activities-devel
    - plasma5support-devel
    - qt6-base-private-devel
rundeps    :
    - kf6-kitemmodels
    - kirigami-addons
    - qt6-quick3d
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
