# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : systemsettings
version    : 6.6.1
release    : 138
source     :
    - https://download.kde.org/stable/plasma/6.6.1/systemsettings-6.6.1.tar.xz : 61fd857755dbdafe80c6afbaab98974f6401c2346ed0afe3855009e5de400e28
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(KF6GuiAddons)
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-krunner-devel
    - plasma-activities-devel
    - qt6-base-private-devel
rundeps    :
    - flatpak-kcm
    - kf6-kirigami
    - wacomtablet
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc
