name       : libicu
version    : '73.2'
release    : 26
source     :
    - https://github.com/unicode-org/icu/releases/download/release-73-2/icu4c-73_2-src.tgz : 818a80712ed3caacd9b652305e01afc7fa167e6f2e94996da44b90c2ab604ce1
license    : MIT
component  : system.base
emul32     : yes
summary    : International Components for Unicode
description: |
    The International Components for Unicode (ICU) package is a mature, widely used set of C/C++ libraries providing Unicode and Globalization support for software applications. ICU is widely portable and gives applications the same results on all platforms.
patterns   :
    - devel :
        - /usr/share/icu
setup      : |
    %patch -p1 -i $pkgfiles/icu4c-73_c-ICU-22512-Fix-broken-TestHebrewCalendarInTemporalLeapYear.patch
    # Required fix for thunderbird 115 to show Calendar and sidebar properly.
    %patch -p1 -i $pkgfiles/ICU-22132.patch

    cd source
    %configure --disable-static
build      : |
    %make -C source
install    : |
    %make_install -C source
check      : |
    %make check -C source
