name       : font-tlwg-ttf
version    : 0.7.3
release    : 4
source     :
    - https://github.com/tlwg/fonts-tlwg/releases/download/v0.7.3/ttf-tlwg-0.7.3.tar.xz : 34052a3332e4f717e218a6b266e3c289ae6b1edb350140383239948e16d8e390
homepage   : https://linux.thai.net/projects/fonts-tlwg
license    :
    - GPL-2.0-only
    - MIT # Waree
component  : desktop.font
summary    : Fonts-TLWG is a collection of Thai scalable fonts available under free licenses.
description: |
    Fonts-TLWG is a collection of Thai scalable fonts available under free licenses.
install    : |
    install -d $installdir/usr/share/fonts/truetype/thai
    cp *.ttf $installdir/usr/share/fonts/truetype/thai
    mv fontconfig/conf.avail $installdir/usr/share/fonts/conf.d
    chmod 00644 -R $installdir/usr/share/fonts
    install -Dm00644 $pkgfiles/tlwg.metainfo.xml $installdir/usr/share/metainfo/tlwg.metainfo.xml