name       : gnome-shell
version    : '45.0'
release    : 100
source     :
    - https://download.gnome.org/sources/gnome-shell/45/gnome-shell-45.0.tar.xz : 3cabe40bdd4e379c7082b39ffa45b8bef5c9cf86408fb0d836e1571c443217cd
homepage   : https://wiki.gnome.org/Projects/GnomeShell
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME Desktop Shell
description: |
    GNOME Shell provides core interface functions like switching windows, launching applications or see your notifications. It takes advantage of the capabilities of modern graphics hardware and introduces innovative user interface concepts to provide a delightful and easy to use experience. GNOME Shell is the defining technology of the GNOME 3 user experience.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gcr-4)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-bluetooth-3.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-keybindings)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libcroco-0.6)
    - pkgconfig(libedataserver-1.2)
    - pkgconfig(libical)
    - pkgconfig(libmutter-13)
    - pkgconfig(libnma)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(xtst)
    - asciidoc
    - sassc
rundeps    :
    - telepathy-logger
    - gnome-session
    - gnome-session-shell
    - switcheroo-control
setup      : |
    %patch -p1 -i $pkgfiles/0001-Ensure-Extensions-app-is-hidden-under-Budgie.patch
    %meson_configure -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
