name       : gnome-backgrounds
version    : '45.0'
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-backgrounds/45/gnome-backgrounds-45.0.tar.xz : cee0e688fbae5ef7a75f335ada2d10779e08ebca9445f1586de32c5a9b6dee2d
homepage   : https://gitlab.gnome.org/GNOME/gnome-backgrounds
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : desktop.gnome
summary    : Default GNOME artwork
description: |
    Default GNOME artwork
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -m00644 $pkgfiles/*.jpg -t $installdir/usr/share/backgrounds/gnome/
