name       : python-comm
version    : 0.1.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/c/comm/comm-0.1.4.tar.gz : 354e40a59c9dd6db50c5cc6b4acc887d82e9603787f83b68c01a80a923984d15
homepage   : https://github.com/ipython/comm
license    : BSD-3-Clause
component  : programming.python
summary    : Python Comm implementation for the Jupyter kernel protocol
description: |
    It provides a way to register a Kernel Comm implementation, as per the Jupyter kernel protocol. It also provides a base Comm implementation and a default CommManager that can be used.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-traitlets
build      : |
    %python3_setup
install    : |
    %python3_install
