name       : librest-07
version    : 0.8.1
release    : 3
source     :
    - https://download.gnome.org/sources/rest/0.8/rest-0.8.1.tar.xz : 0513aad38e5d3cedd4ae3c551634e3be1b9baaa79775e53b2dba9456f15b01c9
homepage   : https://gitlab.gnome.org/GNOME/librest
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : RESTful API library
description: |
    librest was designed to make it easier to access web services that claim to be "RESTful". It includes convenience wrappers for libsoup and libxml to ease remote use of the RESTful API.
emul32     : yes
builddeps  :
    - pkgconfig32(libsoup-2.4)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(libxml-2.0)
    - gtk-doc
setup      : |
    %reconfigure --prefix=/usr --disable-static
build      : |
    %make
install    : |-
    %make_install
