# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : aurorae
version    : 6.6.1
release    : 10
source     :
    - https://download.kde.org/stable/plasma/6.6.1/aurorae-6.6.1.tar.xz : 8d7fc30f43cf8d9aa336f40935fffbfbdb2339ef6307f474222cb1101407d4de
homepage   : https://kde.org/plasma-desktop/
license    :
    - GPL-2.0-or-later
    - MIT
    - CC0-1.0
component  : programming.library
summary    : Themable window decorations for KWin
description: |
    Themable window decorations for KWin
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6UiTools)
    - extra-cmake-modules
    - kdecoration-devel
    - kf6-kcmutils-devel
    - kf6-kcolorscheme-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - kf6-knewstuff-devel
    - kf6-kpackage-devel
    - kf6-ksvg-devel
rundeps    :
    - kf6-ksvg
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
