# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kwallet-pam
version    : 6.6.1
release    : 138
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kwallet-pam-6.6.1.tar.xz : 310e0f7685922d2c5ad4e811f5d1f05ce58334e1ec17209b939cb429fb5d4b27
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libgcrypt)
    - extra-cmake-modules
    - kf6-kwallet-devel
    - socat
rundeps    :
    - socat
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
