# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kgamma
version    : 6.6.1
release    : 43
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kgamma-6.6.1.tar.xz : a2388575b6ab90768a7334cfde04f17f11b036f653074a936b412988526754c9
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Adjust your monitor's gamma settings
description: |
    Adjust your monitor's gamma settings.
builddeps  :
    - pkgconfig(xxf86vm)
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc
replaces   :
    - kgamma5
    - dbginfo : kgamma5-dbginfo
