name       : gnome-session
version    : '45.0'
release    : 41
source     :
    - https://download.gnome.org/sources/gnome-session/45/gnome-session-45.0.tar.xz : 706d2ffcacac38553a3c0185793f5a2b4aac940bb5e789d953c9808163bef2f1
homepage   : https://gitlab.gnome.org/GNOME/gnome-session
license    : GPL-2.0-or-later
summary    :
    - Provides GNOME session core
    - shell : Runtime support for GNOME Shell Session.
description:
    - Provides GNOME session core
    - shell : Runtime support for GNOME Shell Session
component  :
    - desktop.gnome.core
    - shell : desktop.gnome
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - pkgconfig(xtrans)
    - pkgconfig(xtst)
    - docbook-xml
    - xmlto
rundeps    :
    - gsettings-desktop-schemas
    - gvfs
    - udisks
    - upower
    - xdg-user-dirs
    - xdg-user-dirs-gtk
    - xdg-utils
    - shell :
        - gnome-session
        - xdg-desktop-portal-gnome
patterns   :
    - shell :
        - /usr/share/xdg-desktop-portal/gnome-portals.conf
        - /usr/share/xsessions
        - /usr/share/wayland-sessions
replaces   :
    - shell :
        - gnome-session-shell-experimental
setup      : |
    %patch -p1 -i $pkgfiles/0001-Fix-grep-error-for-etc-shells-on-Solus.patch
    %meson_configure -Dsystemd=true \
                     -Dsystemd_journal=true \
                     -Dsystemd_session="default"
build      : |
    %ninja_build
install    : |
    %ninja_install
