# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : geeqie
version    : '2.7'
release    : 27
source     :
    - https://github.com/BestImageViewer/geeqie/releases/download/v2.7/geeqie-2.7.tar.xz : 9b5f342d3cc47782716711e56c3c7a045b4bbeaa653e192d49ce2d5e87ac8106
homepage   : https://www.geeqie.org/
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Geeqie is a lightweight image viewer
description: |
    Geeqie is a lightweight image viewer for Linux, BSDs and compatibles. It can be used as a simple, fast, database-free image viewer, but equally it can be used to manage large collections of images.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(ddjvuapi)
    - pkgconfig(exiv2)
    - pkgconfig(gspell-1)
    - pkgconfig(libarchive)
    - pkgconfig(libffmpegthumbnailer)
    - pkgconfig(libheif)
    - pkgconfig(libjpeg)
    - pkgconfig(libjxl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libraw)
    - pkgconfig(libtiff-4)
    - pkgconfig(lua)
    - pkgconfig(poppler-glib)
    - vim     # for /usr/bin/xxd
rundeps    :
    - gphoto2
    - perl-image-exiftool
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
    %install_license COPYING
