# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kscreen
version    : 6.6.1
release    : 135
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kscreen-6.6.1.tar.xz : 0e8a6b1b3db6ccadf5b22e38b9d0607ab74f9316b10920cdfcd995053e1985db
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
builddeps  :
    - pkgconfig(KF6Screen)
    - pkgconfig(KF6WindowSystem)
    - pkgconfig(Qt6Sensors)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xcb-atom)
    - pkgconfig(xi)
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-ksvg-devel
    - layer-shell-qt-devel
    - libplasma-devel
    - qt6-base-private-devel
rundeps    :
    - kf6-kimageformats
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
