name       : solus-sc
version    : '23'
release    : 50
source     :
    - git|https://github.com/getsolus/solus-sc.git : 06ccc0e1ae1a40b8b58de2f8920de4b50a93325f
homepage   : https://getsol.us
license    : GPL-2.0-only
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - appstream-glib
    - appstream-data
    - at-spi2
    - gvfs
    - libgtk-3
    - python-gobject
    - solus-sc-icons
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
