name       : ghex
version    : '45.0'
release    : 10
source     :
    - https://download.gnome.org/sources/ghex/45/ghex-45.0.tar.xz : 05cecc4561ca40b257c5db31da9f68d696133efc0ae427ed82fb985a986e840e
homepage   : https://wiki.gnome.org/Apps/Ghex
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-only
component  : desktop.gnome
summary    : GHex - a hex editor for GNOME
description: |
    GHex allows the user to load data from any file, view and edit it in either hex or ASCII. Useful for debugging problems with object code or encodings. Also used by kids who cheat at computer games, by adding score or lives to saved games.
builddeps  :
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
