name       : ibus-m17n
version    : 1.4.22
release    : 4
source     :
    - https://github.com/ibus/ibus-m17n/releases/download/1.4.22/ibus-m17n-1.4.22.tar.gz : ce54f981dfc4758fb71a7b26ba546eb8142f24221fb8e76dcb3ede8243c8b619
homepage   : https://github.com/ibus/ibus-m17n
license    : GPL-2.0
component  : desktop.library
summary    : M17N engine for IBus
description: |
    M17N engine for IBus
builddeps  :
    - pkgconfig(ibus-1.0)
    - pkgconfig(m17n-core)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |-
    %make_install
