# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-workspace-wallpapers
version    : 6.6.1
release    : 43
source     :
    - https://download.kde.org/stable/plasma/6.6.1/plasma-workspace-wallpapers-6.6.1.tar.xz : 60fb91522ea3249fb285559c4003bccef3d01e561b977bfa95ee6ba40bc4269b
homepage   : https://kde.org/plasma-desktop
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : desktop.kde
summary    : Wallpapers for Plasma Workspaces
description: |
    Wallpapers for Plasma Workspaces
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
