# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libfyaml
version    : 0.9.4
release    : 2
source     :
    - https://github.com/pantoniou/libfyaml/releases/download/v0.9.4/libfyaml-0.9.4.tar.gz : dac2b0af7b757b32a4fa7c6493d85d0f7dea6effd20ae4352570b6a450b9e5fb
homepage   : https://github.com/pantoniou/libfyaml
license    : MIT
component  : programming.library
summary    : Fully feature complete YAML parser and emitter, supporting the latest YAML spec and passing the full YAML testsuite.
description: |
    A fancy 1.2 YAML and JSON parser/writer.
    Fully feature complete YAML parser and emitter, supporting the latest YAML spec and passing the full YAML testsuite.
    It is designed to be very efficient, avoiding copies of data, and has no artificial limits like the 1024 character limit for implicit keys.
builddeps  :
    - pkgconfig(yaml-0.1)
checkdeps  :
    - pkgconfig(check)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
