# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ccache
version    : 4.12.3
release    : 32
source     :
    - https://github.com/ccache/ccache/releases/download/v4.12.3/ccache-4.12.3.tar.xz : c8e3ef79531966ecfa05bd1666c483b473df9af00896935cc468cb5ed573c16e
homepage   : https://ccache.dev/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : compiler cache
description: |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
builddeps  :
    - pkgconfig(fmt)
    - pkgconfig(libxxhash)
    - pkgconfig(libzstd)
    - asciidoctor
setup      : |
    %patch -p1 -i $pkgfiles/0001-ccache-Add-vendor-dir.patch
    %cmake_ninja -DCMAKE_INSTALL_SYSCONFDIR="/etc/ccache" \
                 -DVENDORDIR="/usr/share/defaults/etc/ccache" \
                 -DREDIS_STORAGE_BACKEND=OFF \
                 -DENABLE_TESTING=OFF \
                 -DDEPS=LOCAL
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -d $installdir/%libdir%/ccache/bin

    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ c++ x86_64-solus-linux-c++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done

    install -Dm00644 $pkgfiles/ccache.conf -t $installdir/usr/share/defaults/etc/ccache
# Need to package doctest before we can re-enable the test-suite
# check      : |
#     %ninja_check
