# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : gnuplot
version    : 6.0.4
release    : 30
source     :
    - https://sourceforge.net/projects/gnuplot/files/gnuplot/6.0.4/gnuplot-6.0.4.tar.gz : 458d94769625e73d5f6232500f49cbadcb2b183380d43d2266a0f9701aeb9c5b
homepage   : https://sourceforge.net/projects/gnuplot/
license    : gnuplot
component  : programming
summary    : Gnuplot is a portable command-line driven graphing utility
description: |
    Gnuplot is a portable command-line driven graphing utility
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(pangocairo)
    - pkgconfig(x11)
    - wxwidgets-devel
setup      : |
    export CFLAGS="${CFLAGS} -std=gnu17"
    %configure --with-readline=gnu --with-qt=no
build      : |
    %make
install    : |
    %make_install

