name       : tepl
version    : 6.8.0
release    : 20
source     :
    - https://download.gnome.org/sources/tepl/6.8/tepl-6.8.0.tar.xz : 46e6e5f1bfdbc52e5956f06add575e9c7697c673d53d3803dfe768f490b560f0
homepage   : https://gitlab.gnome.org/swilmet/tepl
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
description: |
    Tepl is a library that eases the development of GtkSourceView-based text editors and IDEs.
builddeps  :
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(icu-io)
    - pkgconfig(libgedit-amtk-5)
    - pkgconfig(libgedit-gtksourceview-300)
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
