name       : graphviz
version    : 9.0.0
release    : 33
source     :
    - https://gitlab.com/graphviz/graphviz/-/archive/9.0.0/graphviz-9.0.0.tar.gz : 504d19b5d0e5398a57e9d9de42393f90b9e79aff0969b4ebc3b891ccb39602ed
homepage   : https://www.graphviz.org
license    : EPL-1.0
component  : multimedia.graphics
clang      : yes
summary    : Graphviz is open source graph visualization software
description: |
    Graphviz is open source graph visualization software
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(glu)
    - pkgconfig(glut)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gts)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwebp)
    - pkgconfig(pango)
    - pkgconfig(poppler)
    - pkgconfig(xaw6)
    - ghostscript-devel
    - groff
patterns   :
    - devel :
        - /usr/lib64/graphviz/*.so
setup      : |
    %patch -p1 -i $pkgfiles/ghostscript918.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$installdir/usr/lib64
    $installdir/usr/bin/dot -c
