# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kmenuedit
version    : 6.6.1
release    : 132
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kmenuedit-6.6.1.tar.xz : 673cca2caf62a7982de98fcbd10e879f9febb9444d94198f6388df78aea9f5f1
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE Plasma menu editor
description: |
    KDE Plasma menu editor.
builddeps  :
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - kf6-sonnet-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
