name       : seafile
version    : 9.0.4
release    : 30
source     :
    - https://github.com/haiwen/seafile/archive/refs/tags/v9.0.4.tar.gz : 6374569f05eb6f8d1632fbfc4356754078308e2a0605aed4e798219b4eafbb51
homepage   : https://www.seafile.com/
license    :
    - GPL-2.0-only
    - OpenSSL
component  : network
summary    : Seafile Server and Libraries
description: |
    File syncing and sharing software with file encryption and group sharing, emphasis on reliability and high performance.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libevent)
    - pkgconfig(libsearpc)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %autogen --disable-static --with-python3 --disable-ws
build      : |
    %make
install    : |
    %make_install
