name       : unicode-character-database
version    : 15.1.0
release    : 10
source     :
    - https://www.unicode.org/Public/zipped/15.1.0/UCD.zip : cb1c663d053926500cd501229736045752713a066bd75802098598b7a7056177
    - https://www.unicode.org/Public/zipped/15.1.0/Unihan.zip : a0226610e324bcf784ac380e11f4cbf533ee1e6b3d028b0991bf8c0dc3f85853
    - https://sources.getsol.us/Emoji.zip : bd88138382a35a2d87ff5e6e5bbbd30549791d055c2daef5fc362672d9ab10a3
    - https://github.com/fujiwarat/cldr-emoji-annotation/releases/download/37.0_13.0_0_2/cldr-emoji-annotation-37.0_13.0_0_2.tar.gz : 7a24ea3dc17b814fbe8ee1127e1036679098ef2991b9266d738d375554210d13
license    : MIT
homepage   : https://www.unicode.org
extract    : no
component  : programming
summary    : The Unicode Character Database (UCD)
description: |
    The Unicode Character Database (UCD) consists of a number of data files listing Unicode character properties and related data.
builddeps  :
    - unzip
patterns   :
    - /*
setup      : |
    mkdir ucd
    unzip $sources/UCD.zip -d ucd/
    unzip $sources/Unihan.zip -d ucd/
    tar xf $sources/cldr-*
build      : |
    cd $workdir/cldr-*
    %reconfigure
    %make
install    : |
    install -dm00644 $installdir/usr/share/unicode-character-database/
    install -dm00644 $installdir/usr/share/unicode/emoji
    cp -R $workdir/ucd/* $installdir/usr/share/unicode-character-database/
    cp $sources/U*.zip $installdir/usr/share/unicode-character-database/
    ln -s /usr/share/unicode-character-database $installdir/usr/share/unicode/ucd
    unzip $sources/Emoji.zip
    cp -R Emoji/* $installdir/usr/share/unicode/emoji/
    cd $workdir/cldr-*
    %make_install
