name       : cinelerra-gg
version    : 5.1.2023.09.30
release    : 35
source     :
    - https://cinelerra-gg.org/download/pkgs/src/cin_5.1.20230930-src.tgz : 4164abb8df526213d3dd071d79410697a342a689b709f291c8d8c28ec7cb76d6
license    : GPL-2.0-or-later
component  : multimedia.video
homepage   : https://cinelerra-gg.org
summary    : Professional open source video editor comparable to Lightworks in its features
description: |
    Cinelerra is an NLE – Non-Linear Editor – for Linux that provides a way to compose audio and video media. Besides editing, it can be used as an audio/video player, for recording audio or video to include broadcast television programs, creating dvd/bluray media, and touching up old photos. Because cinelerra has many features for uncompressed content, high resolution processing, and compositing, using cinelerra can be quite complex. However, with only a little bit of introduction, even a novice will be able to create simple artful videos.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(aom)
    - pkgconfig(audiofile)
    - pkgconfig(bzip2)
    - pkgconfig(dav1d)
    - pkgconfig(dotconf)
    - pkgconfig(ffnvcodec)
    - pkgconfig(fftw3f)
    - pkgconfig(flac++)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libavc1394)
    - pkgconfig(libdv)
    - pkgconfig(libiec61883)
    - pkgconfig(liblzma)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpulse-simple)
    - pkgconfig(libthai)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libusb-1.0)
    - pkgconfig(libva-wayland)
    - pkgconfig(libwebp)
    - pkgconfig(lilv-0)
    - pkgconfig(mjpegtools)
    - pkgconfig(ncursesw)
    - pkgconfig(OpenEXR)
    - pkgconfig(opus)
    - pkgconfig(sndfile)
    - pkgconfig(suil-0)
    - pkgconfig(theora)
    - pkgconfig(twolame)
    - pkgconfig(vdpau)
    - pkgconfig(vorbis)
    - pkgconfig(vpx)
    - pkgconfig(x264)
    - pkgconfig(x265)
    - pkgconfig(xorg-server)
    - pkgconfig(xv)
    - doxygen
    - giflib-devel
    - inkscape
    - ladspa-devel
    - lame-devel
    - liba52dec-devel
    - yasm
rundeps    :
    - dvdauthor
    - libva-intel-driver
    - udftools
setup      : |
    %autogen
build      : |
    %make
install    : |
    unset LD_PRELOAD
    make -j1 install DESTDIR="$installdir" # it fails with DESTDIR="%installroot%"
