name       : libsigc++30
version    : 3.6.0
release    : 5
source     :
    - https://download.gnome.org/sources/libsigc++/3.6/libsigc++-3.6.0.tar.xz : c3d23b37dfd6e39f2e09f091b77b1541fbfa17c4f0b6bf5c89baef7229080e17
homepage   : https://github.com/libsigcplusplus/libsigcplusplus
license    : LGPL-3.0-or-later
component  : desktop.gnome.core
summary    : The libsigc++30 package implements the libsigc++ 3.x ABI for its typesafe callback system for standard C++.
description: |
    The libsigc++30 package implements the libsigc++ 3.x ABI for its typesafe callback system for standard C++.
patterns   :
    - devel :
        - /usr/lib64/sigc++-3.0/include
setup      : |
    %meson_configure -Dbuild-documentation=false -Dbuild-examples=false
build      : |
    %ninja_build
install    : |
    %ninja_install
