name       : nv-codec-headers
version    : 11.1.5.3
release    : 5
source     :
    - https://github.com/FFmpeg/nv-codec-headers/releases/download/n11.1.5.3/nv-codec-headers-11.1.5.3.tar.gz : 2974b91062197e0527dffa3aadd8fe3bfa6681ae45f5ff9181bc0ca6479abd59
license    : MIT
component  : multimedia.library
homepage   : https://github.com/FFmpeg/nv-codec-headers
summary    : Headers for Nvidia Video Codec API.
description: |
    FFmpeg version of headers required to interface with Nvidias codec APIs.
install    : |
    %make_install PREFIX='/usr'
