name       : geoclue
version    : 2.7.1
release    : 23
source     :
    - https://gitlab.freedesktop.org/geoclue/geoclue/-/archive/2.7.1/geoclue-2.7.1.tar.gz : 58de0c6f16fee4972ec6e250c9fc2f9d35d13cb83f9cca8ac7cbd976d8d6a1d1
homepage   : https://gitlab.freedesktop.org/geoclue/geoclue/-/wikis/home
license    : GPL-2.0-or-later
component  : programming
summary    : GeoInformation service
description: |
    GeoClue is a modular geoinformation service built on top of the D-Bus messaging system. The goal of the GeoClue project is to make creating location-aware applications as simple as possible.
builddeps  :
    - pkgconfig(avahi-glib)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(mm-glib)
    - vala
replaces   :
    - devel : libgeoclue-devel
    - libgeoclue
setup      : |
    %patch -p1 -i $pkgfiles/0001-Support-a-stateless-configuration.patch
    %patch -p1 -i $pkgfiles/0001-Add-redshift-to-default-config.patch
    %meson_configure \
        -Ddbus-sys-dir=/usr/share/dbus-1/system.d/ \
        -Ddemo-agent=true \
        -Dgtk-doc=false \
        -Dmozilla-api-key=bb829e84-adeb-4e95-8279-4458e788252f \
        -Dsystemd-system-unit-dir=%libdir%/systemd/system/
build      : |
    %ninja_build
install    : |
    %ninja_install
