# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kquickimageeditor
version    : 0.6.0
release    : 8
source     :
    - https://download.kde.org/stable/kquickimageeditor/kquickimageeditor-0.6.0.tar.xz : 11ed4ce1c164a8b6d50bbc1548b5849ab75d5fb837619b90f2cea51ed122547a
license    :
    - BSD-2-Clause
    - CC0-1.0
    - LGPL-2.1-or-later
component  : programming.library
homepage   : https://invent.kde.org/libraries/kquickimageeditor
summary    : KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
description: |
    KQuickImageEditor is a set of QtQuick components providing basic image editing capabilities.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(opencv4)
    - extra-cmake-modules
    - kf6-kconfig-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
