name       : python-moddb
version    : 0.9.0
release    : 3
source     :
    - https://pypi.io/packages/source/m/moddb/moddb-0.9.0.tar.gz : c78f94d69062e5f12098e7bcecb1b1479cbab359b157d75225461d7af3750e8e
homepage   : https://github.com/ClementJ18/moddb
license    : MIT
component  : programming.python
summary    : A scrapper for ModDB Mod and Game pages
description: |
    The goal of this library is to be able to navigate ModDB purely programmatically through scraping and parsing of the various models present on the website.
rundeps    :
    - python-beautifulsoup4
    - python-pyrate-limiter
    - python-requests
    - python-toolz
build      : |
    %python3_setup
install    : |
    %python3_install
