name       : libgedit-gtksourceview
version    : 299.0.4
release    : 1
source     :
    - https://gedit-technology.net/tarballs/libgedit-gtksourceview/libgedit-gtksourceview-299.0.4.tar.xz : 7453a1cce2f6d58871644d2203ecdbbb043050886170ebea376c1cf6e27f86d8
homepage   : https://gedit-technology.net/
license    : lgpl-2.1-or-later
component  : desktop.gnome
summary    : libgedit-gtksourceview is a library that extends GtkTextView, the standard GTK widget for multiline text editing.
description: |
    libgedit-gtksourceview is a library that extends GtkTextView, the standard GTK widget for multiline text editing.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gtk-doc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
