name       : libva
version    : 2.20.0
release    : 28
source     :
    - https://github.com/intel/libva/archive/refs/tags/2.20.0.tar.gz : 117f8d658a5fc9ea406ca80a3eb4ae1d70b15a54807c9ed77199c812bed73b60
license    : MIT
component  : xorg.display
homepage   : https://github.com/intel/libva
summary    : Libva is an implementation for VA-API (Video Acceleration API)
description: |
    VA-API is an open-source library and API specification, which provides access to graphics hardware acceleration capabilities for video processing. It consists of a main library and driver-specific acceleration backends for each supported hardware vendor.
builddeps  :
    - pkgconfig32(gl)
    - pkgconfig32(libdrm)
    - pkgconfig32(wayland-client)
    - pkgconfig32(x11)
    - pkgconfig32(xext)
    - pkgconfig32(xfixes)
emul32     : yes
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
