name       : libcairo
version    : 1.18.0
release    : 53
source     :
    - https://cairographics.org/releases/cairo-1.18.0.tar.xz : 243a0736b978a33dee29f9cca7521733b78a65b5418206fef7bd1c3d4cf10b64
license    : LGPL-2.1-or-later
component  : desktop.library
homepage   : https://cairographics.org/
summary    : cairo (2D graphics library)
description: |
    Cairo is a 2D graphics library with support for multiple output devices such as X, Quartz, Win32, image buffers, PS, PDF, and SVG.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(pixman-1)
    - pkgconfig32(xcb-render)
    - pkgconfig32(xext)
    - pkgconfig32(xrender)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
    - gtk-doc
replaces   :
    - cairo
    - devel : cairo-devel
    - docs : cairo-docs
patterns   :
    - devel : /usr/bin
setup      : |
    %apply_patches
    %meson_configure \
        -Dfontconfig=enabled \
        -Dfreetype=enabled \
        -Dpng=enabled \
        -Dxlib=enabled \
        -Dxcb=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
