# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma5support
version    : 6.6.1
release    : 44
source     :
    - https://download.kde.org/stable/plasma/6.6.1/plasma5support-6.6.1.tar.xz : af922987aee0a6c1bd026e8b3430d1eb150aef8306e4ca687e13b8bcd5e25cef
homepage   : https://invent.kde.org/plasma/plasma5support
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.libraries
summary    : Support components for porting from KF5/Qt5 to KF6/Qt6
description: |
    Support components for porting from KF5/Qt5 to KF6/Qt6
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(xfixes)
    - extra-cmake-modules
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kguiaddons-devel
    - kf6-kholidays-devel
    - kf6-ki18n-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kservice-devel
    - kf6-kunitconversion-devel
    - kf6-networkmanager-qt-devel
    - kf6-solid-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma-activities-devel
    - qt6-base-private-devel
clang      : true
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
