# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : knighttime
version    : 6.6.1
release    : 8
source     :
    - https://download.kde.org/stable/plasma/6.6.1/knighttime-6.6.1.tar.xz : e3a65155d7bd2d71309c1e54e9047f15eb407030e1bd4db913406b8c59863d39
homepage   : https://kde.org/plasma-desktop/
license    : LGPL-2.0-or-later
summary    : Helpers for scheduling the dark-light cycle
description: |
    Helpers for scheduling the dark-light cycle
builddeps  :
    - pkgconfig(Qt6Positioning)
    - extra-cmake-modules
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-kholidays-devel
    - kf6-ki18n-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - thin-lto
    - speed
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/share/dbus-1/interfaces/
