name       : python-mock
version    : 5.1.0
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/m/mock/mock-5.1.0.tar.gz : 5e96aad5ccda4718e0a229ed94b2024df75cc2d55575ba5762d31f5767b8767d
homepage   : https://github.com/testing-cabal/mock
license    : BSD-2-Clause
component  : programming.python
summary    : Rolling backport of unittest.mock for all Pythons
description: |
    mock is a library for testing in Python. It allows you to replace parts of your system under test with mock objects and make assertions about how they have been used.
builddeps  :
    - pbr
    - python-six
rundeps    :
    - pbr
    - python-six
setup      : |
    %python3_setup
install    : |
    %python3_install
