# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : spectacle
version    : 6.6.1
release    : 119
source     :
    - https://download.kde.org/stable/plasma/6.6.1/spectacle-6.6.1.tar.xz : 6ae033482f20fe847610ef4e2bef81eab2b483d7f5f230c5cdf873273695ebaf
homepage   : https://kde.org/applications/utilities/org.kde.spectacle
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE Screenshot Utility
description: |
    Spectacle is screenshot taking utility for the KDE desktop. Spectacle can also be used in non-KDE X11 desktop environments.
builddeps  :
    - pkgconfig(KF6GuiAddons)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(opencv4)
    - pkgconfig(x11)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-util)
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kxmlgui-devel
    - kf6-prison-devel
    - kf6-purpose-devel
    - kpipewire-devel
    - kquickimageeditor-devel
    - layer-shell-qt-devel
    - plasma-wayland-protocols-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rfv $installdir/usr/share/doc
