# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kpipewire
version    : 6.6.1
release    : 59
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kpipewire-6.6.1.tar.xz : def29bb3288c2a800b182e8e4b508c34abcff8ff22226bacbb56a5eac551aab9
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Components relating to pipewire use in Plasma
description: |
    Components relating to pipewire use in Plasma
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libavcodec)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libva)
    - extra-cmake-modules
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - qt6-base-private-devel
rundeps    :
    - devel :
        # For epoxy/egl.h
        - libepoxy-devel
        - pipewire-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
