# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : print-manager
version    : 6.6.1
release    : 121
source     :
    - https://download.kde.org/stable/plasma/6.6.1/print-manager-6.6.1.tar.xz : 2cc4be33015883b18aef31eaa33a858f8627fb69bd4918d977cbc16580c503d0
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
libsplit   : false
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(cups)
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - libplasma-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
