name       : ulauncher
version    : 5.15.4
release    : 16
source     :
    - https://github.com/Ulauncher/Ulauncher/releases/download/5.15.4/ulauncher_5.15.4.tar.gz : e691296272451d02847d3bded3b9e01550c038cf7e930af1ea1737d20130b24a
homepage   : https://ulauncher.io/
license    : GPL-3.0-or-later
component  : desktop
summary    : Linux Application Launcher
description: |
    Ulauncher is a fast application launcher for Linux. It's is written in Python, using GTK+.
builddeps  :
    - python-distutils-extra
rundeps    :
    - keybinder
    - libwebkit-gtk
    - python-gobject
    - python-inotify
    - python-levenshtein
    - python-pygithub
    - python-websocket-client
    - python3-dbus
    - pyxdg
setup      : |
    %patch -p1 -i $pkgfiles/shutup-distutils.patch
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -r $installdir/usr/share/doc

    # We don't have wmctrl because it is DOA
    rm -f $installdir/usr/bin/ulauncher-toggle
