name       : atkmm-2.36
version    : 2.36.2
release    : 1
source     :
    - https://download.gnome.org/sources/atkmm/2.36/atkmm-2.36.2.tar.xz : 6f62dd99f746985e573605937577ccfc944368f606a71ca46342d70e1cdae079
homepage   : https://gtkmm.org
license    : LGPL-2.0-or-later
component  : desktop.gtk
summary    : C++ bindings to atk
description: |
    C++ bindings to atk
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(glibmm-2.68)
    - pkgconfig(sigc++-3.0)
patterns   :
    - devel :
        - /usr/lib64/atkmm-2.36
setup      : |
    %meson_configure -Dbuild-documentation='false'
build      : |
    %ninja_build
install    : |
    %ninja_install
