name       : d-spy
version    : 1.8.0
release    : 4
source     :
    - https://download.gnome.org/sources/d-spy/1.8/d-spy-1.8.0.tar.xz : f89d795d0686d82da1dceb236148f7ce54d5ca78f0b98e0f1336b263a5afcea1
homepage   : https://gitlab.gnome.org/GNOME/d-spy
license    : GPL-3.0-or-later
component  : system.utils
summary    : System D-BUS viewer
description: |
    System D-BUS viewer. It's like d-feet, but written in C and blisteringly fast. Also comes with a library for IDE integration.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
