# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xdebug
version    : 3.5.1
release    : 10
source     :
    - https://github.com/xdebug/xdebug/archive/refs/tags/3.5.1.tar.gz : 8fd5908d881a588688bd224c7e603212405fa700dc50513d0d366141c27cc78a
homepage   : https://xdebug.org/
license    : Xdebug-1.03
summary    : Xdebug is a debugger and profiler for PHP.
component  : programming.tools
description: |
    Xdebug is a debugger and profiler for PHP.
builddeps  :
    - php-devel
rundeps    :
    - php
setup      : |
    phpize
    aclocal
    autoconf
    %configure --enable-xdebug
build      : |
    %make
install    : |
    install -Dm00644 modules/xdebug.so $installdir/usr/lib64/php/modules/xdebug.so
    install -Dm00644 $pkgfiles/xdebug.ini $installdir/etc/php/conf.d/xdebug.ini
    %install_license LICENSE
