name       : gnome-text-editor
version    : 45.0
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-text-editor/45/gnome-text-editor-45.0.tar.xz : 47b3fbe4900eb204413d9af3ae8e0ecd06728d2ac15d02b1a050d02d47226bc1
homepage   : https://gitlab.gnome.org/GNOME/gnome-text-editor
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : A simple text editor for the GNOME desktop.
description: |
    A simple text editor for the GNOME desktop.
builddeps  :
    - pkgconfig(editorconfig)
    - pkgconfig(enchant-2)
    - pkgconfig(gtk4)
    - pkgconfig(gtksourceview-5)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
