name       : cairomm-1.16
version    : 1.18.0
release    : 1
source     :
    - https://www.cairographics.org/releases/cairomm-1.18.0.tar.xz : b81255394e3ea8e8aa887276d22afa8985fc8daef60692eb2407d23049f03cfb
homepage   : https://cairographics.org/cairomm
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : C++ bindings to cairo.
description: |
    C++ bindings to cairo
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(sigc++-3.0)
    - doxygen
    - graphviz
patterns   :
    - docs :
        - /usr/share/devhelp
        - /usr/share/doc
    - devel:
        - /usr/lib64/cairomm-1.16
setup      : |
    %meson_configure -Dbuild-documentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install