name       : gnome-shell-extension-appindicator
version    : '57'
release    : 2
source     :
    - https://github.com/ubuntu/gnome-shell-extension-appindicator/archive/refs/tags/v57.tar.gz : 788fa3ff2f8525efbd794bffd0fcec3d77c9c1cbfcff0fadeb93b4925751ca41
homepage   : https://github.com/ubuntu/gnome-shell-extension-appindicator
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : AppIndicator/KStatusNotifierItem/Legacy icons support for GNOME Shell
description: |
    This extension integrates Ubuntu AppIndicators and KStatusNotifierItems (KDE's blessed successor of the systray) into GNOME Shell. Including support for legacy tray icons.
builddeps  :
    - jq
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
replaces   :
    - gnome-shell-extension-topicons-plus
