# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ocean-sound-theme
version    : 6.6.1
release    : 42
source     :
    - https://download.kde.org/stable/plasma/6.6.1/ocean-sound-theme-6.6.1.tar.xz : afd67bb12d61d6066454690023ff5692e3990af655e2700164df3571bfe850ac
homepage   : https://kde.org/plasma-desktop
license    :
    - BSD-2-Clause
    - CC-BY-SA-4.0
    - CC0-1.0
component  : desktop
summary    : Ocean Sound Theme for Plasma
description: |
    Ocean Sound Theme for Plasma
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
