name       : source-code-pro
version    : '2.038'
release    : 6
source     :
    - https://github.com/adobe-fonts/source-code-pro/archive/refs/tags/2.038R-ro/1.058R-it/1.018R-VAR.tar.gz : d8f879fefd66ecb7291ea2d73984b9c0a97fb499424e58290ba6b81787d0c725
license    : SIL-1.1
component  : desktop.font
homepage   : https://fonts.adobe.com/fonts/source-code-pro
summary    : Source Code Pro Font Set
description: |
    Source Code Pro Font Set
install    : |
    mkdir -p $installdir/usr/share/fonts/truetype/source-code-pro
    install -m 0644 TTF/*.ttf %installroot%/usr/share/fonts/truetype/source-code-pro/
    install -Dm00644 $pkgfiles/source-code-pro.metainfo.xml $installdir/usr/share/metainfo/source-code-pro.metainfo.xml
