name       : python-jupyterlab-server
version    : 2.25.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/39/50/e6ed3c392bf304ccbde96b4f2ae7da6f5f7c758deeaf95e117647605c136/jupyterlab_server-2.25.0.tar.gz : 77c2f1f282d610f95e496e20d5bf1d2a7706826dfb7b18f3378ae2870d272fb7
homepage   : https://github.com/jupyterlab/jupyterlab_server
license    : BSD-3-Clause
component  : programming.python
summary    : A set of server components for JupyterLab and JupyterLab like applications
description: |
    JupyterLab Server sits between JupyterLab and Jupyter Server, and provides a set of REST API handlers and utilities that are used by JupyterLab. It is a separate project in order to accommodate creating JupyterLab-like applications from a more limited scope.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-json5
    - python-jsonschema
    - python-jupyter-server
    - python-jinja
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
