# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : sddm-kcm
version    : 6.6.1
release    : 129
source     :
    - https://download.kde.org/stable/plasma/6.6.1/sddm-kcm-6.6.1.tar.xz : de78ac166cf5a34784cd1d474d78042bf4e76a3c579c87ea0c831ab5cfd19bb8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(xcb-cursor)
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
