name       : sqlite3
version    : 3.43.2
release    : 47
source     :
    - https://www.sqlite.org/2023/sqlite-autoconf-3430200.tar.gz : 6d422b6f62c4de2ca80d61860e3a3fb693554d2f75bb1aaca743ccc4d6f609f0
license    : Public-Domain
component  : system.base
optimize   : speed
emul32     : yes
summary    : Self contained SQL package
description: |
    The SQLite package is a software library that implements a self-contained, serverless, zero-configuration, transactional SQL database engine.
setup      : |
    ex_opts=""
    if [[ -z "${EMUL32BUILD}" ]]; then
        ex_opts="--enable-readline"
    fi

    %configure --disable-static \
        --enable-dynamic-extensions \
        --enable-fts3 \
        --enable-fts4 \
        --enable-fts5 \
        --enable-rtree \
        --enable-threadsafe \
        $ex_opts \
        CFLAGS="$CFLAGS \
        -DSQLITE_ENABLE_COLUMN_METADATA=1 \
        -DSQLITE_ENABLE_DBPAGE_VTAB=1 \
        -DSQLITE_ENABLE_DBSTAT_VTAB=1 \
        -DSQLITE_ENABLE_FTS3_PARENTHESIS=1 \
        -DSQLITE_ENABLE_STMTVTAB=1 \
        -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 \
        -DSQLITE_SECURE_DELETE=1"
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 sqlite3.1 $installdir/usr/share/man/man1/sqlite3.1
