name       : python-attrs
version    : 23.1.0
release    : 19
source     :
    - https://files.pythonhosted.org/packages/source/a/attrs/attrs-23.1.0.tar.gz : 6279836d581513a26f1bf235f9acd333bc9115683f14f7e8fae46c98fc50e015
homepage   : https://www.attrs.org/en/stable/
license    : MIT
component  : programming.python
summary    : Python Classes Without Boilerplate
description: |
    attrs is the Python package that will bring back the joy of writing classes by relieving you from the drudgery of implementing object protocols (aka dunder methods).
builddeps  :
    - python-build
    - python-cloudpickle             # check
    - python-hypothesis              # check
    - python-hatch-fancy-pypi-readme
    - python-hatch-vcs
    - python-installer
    - python-pytest                  # check
    - python-zope.interface          # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
