# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libgcrypt
version    : 1.12.1
release    : 31
source     :
    - https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.12.1.tar.bz2 : 7df5c08d952ba33f9b6bdabdb06a61a78b2cf62d2122c2d1d03a91a79832aa3c
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.base
homepage   : https://gnupg.org/software/libgcrypt/index.html
summary    : GNU's basic cryptographic library
description: |
    Libgcrypt is GNU's basic cryptographic library.
emul32     : true
optimize   :
    - size
    - lto
patterns   :
    - devel : /usr/share/aclocal
builddeps  :
    - pkgconfig32(gpg-error)
setup      : |
    %configure --with-gpg-error-prefix=/usr \
               --enable-noexecstack
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
