name       : libgtksourceview3
version    : 3.24.11
release    : 7
source     :
    - https://download.gnome.org/sources/gtksourceview/3.24/gtksourceview-3.24.11.tar.xz : 691b074a37b2a307f7f48edc5b8c7afa7301709be56378ccf9cc9735909077fd
homepage   : https://wiki.gnome.org/Projects/GtkSourceView
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Legacy 3.x syntax highlighting text editing C library
description: |
    GtkSourceView3 is the legacy 3.x series of the portable C library that extends the standard GTK+ framework for multiline text editing with support for configurable syntax highlighting, unlimited undo/redo, UTF-8 compliant caseless searching, printing and other features typical of a source code editor.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - gtk-doc
    - valadoc
setup      : |
    %reconfigure --disable-static --enable-vala
build      : |
    %make
install    : |
    %make_install
