name       : libadwaita
version    : 1.4.0
release    : 10
source     :
    - https://download.gnome.org/sources/libadwaita/1.4/libadwaita-1.4.0.tar.xz : e51a098a54d43568218fc48fcf52e80e36f469b3ce912d8ce9c308a37e9f47c2
homepage   : https://gnome.pages.gitlab.gnome.org/libadwaita/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Building blocks for modern adaptive GNOME applications.
description: |
    Building blocks for modern adaptive GNOME applications.
builddeps  :
    - pkgconfig(appstream)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk4)
    - sassc
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
