name       : librsvg
version    : 2.57.0
release    : 54
source     :
    - https://download.gnome.org/sources/librsvg/2.57/librsvg-2.57.0.tar.xz : 335fe2e0c2cbf1b7bf0668651224a23e135451f0b1793cd813649be2bffa74e8
homepage   : https://wiki.gnome.org/Projects/LibRsvg
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Library to render SVG files using Cairo
description: |
    A small library to render Scalable Vector Graphics (SVG), associated with the GNOME Project. It renders SVG files to Cairo surfaces. Cairo is the 2D, antialiased drawing library that GNOME uses to draw things to the screen or to generate output for printing
optimize   : speed
networking : yes
emul32     : yes
patterns   :
    - devel :
        - /usr/bin
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(libpng)
    - pkgconfig32(libxml-2.0)
    - pkgconfig32(pango)
    - pkgconfig32(xdamage)
    - pkgconfig32(xshmfence)
    - cargo
    - gi-docgen
    - python-docutils # man
    - vala
setup      : |
    flags='--disable-static --enable-vala'
    if [ ! -z $EMUL32BUILD ]; then
        flags+=' --host=i686-unknown-linux-gnu'
    fi
    %configure $flags
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
