name       : languagetool
version    : '6.3'
release    : 8
source     :
    - https://github.com/languagetool-org/languagetool/archive/refs/tags/v6.3-branch.tar.gz : c15c0dbb9ef889e40e7d88129f90e1570319904214f27d707c92577ab8865c86
homepage   : https://languagetool.org
license    : LGPL-2.1-only
component  : office.viewers
summary    : Style and Grammar Checker for 25+ Languages
description: |
    LanguageTool is an Open Source proofreading software for English, French, German, Polish, Russian, and more than 20 other languages. It finds many errors that a simple spell checker cannot detect.
builddeps  :
    - apache-maven
    - openjdk-17
rundeps    :
    - openjdk-17
networking : yes
environment: |
    JAVA_HOME=/usr/lib64/openjdk-17
    PATH=$JAVA_HOME/bin:$PATH
build      : |
    $workdir/build.sh languagetool-standalone package -DskipTests -Dmaven.repo.local=$workdir/.m2 -Dmaven.gitcommitid.skip=true
install    : |
    install -dDm00755 $installdir/usr/share/languagetool/{libs,META-INF,org}
    cp $workdir/languagetool-standalone/target/LanguageTool-$version/LanguageTool-$version/*.jar $installdir/usr/share/languagetool/
    cp $workdir/languagetool-standalone/target/LanguageTool-$version/LanguageTool-$version/libs/*.jar $installdir/usr/share/languagetool/libs/
    cp -R $workdir/languagetool-standalone/target/LanguageTool-$version/LanguageTool-$version/META-INF/* $installdir/usr/share/languagetool/META-INF/
    cp -R $workdir/languagetool-standalone/target/LanguageTool-$version/LanguageTool-$version/org/* $installdir/usr/share/languagetool/org/
    install -Dm00755 $pkgfiles/languagetool -t $installdir/usr/bin
check      : |
    #mvn test -Dmaven.repo.local=$workdir/.m2
