# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xauth
version    : 1.1.5
release    : 11
source     :
    - https://www.x.org/releases/individual/app/xauth-1.1.5.tar.gz : cf94d3ee1fac0b3d9f9fb8ec5f95bd5f82e7958f929f092ec98c00fc2b7aef68
license    : GPL-3.0
component  : xorg.apps
homepage   : https://www.x.org/
summary    : X.Org Applications - xauth
description: |
    The xauth command is usually used to edit and display the authorization information used in connecting to the X server. This program extracts authorization records from one machine and merge them into another (for example, when using remote logins or granting access to other users).
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xau)
    - pkgconfig(xext)
    - pkgconfig(xmuu)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
