name       : libwebkit-gtk5
version    : 2.42.1
release    : 13
source     :
    - https://webkitgtk.org/releases/webkitgtk-2.42.1.tar.xz : 6f41fac9989d3ee51c08c48de1d439cdeddecbc757e34b6180987d99b16d2499
homepage   : https://webkitgtk.org
license    : LGPL-2.1-only
component  : desktop.web
summary    : Web rendering engine
description: |
    The WebKitGTK+ package is the port of the portable web rendering engine WebKit to the GTK+ platform.
clang      : no
optimize   :
    - no-symbolic
    - speed
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(epoxy)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gbm)
    - pkgconfig(gnutls)
    - pkgconfig(gstreamer-gl-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gstreamer-transcoder-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(icu-uc)
    - pkgconfig(lcms2)
    - pkgconfig(libavif)
    - pkgconfig(libgcrypt)
    - pkgconfig(libjpeg)
    - pkgconfig(libnotify)
    - pkgconfig(libopenjp2)
    - pkgconfig(libseccomp)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(libwebp)
    - pkgconfig(libwoff2dec)
    - pkgconfig(libxslt)
    - pkgconfig(ruby-3.2)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wpebackend-fdo-1.0)
    - pkgconfig(xt)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - bubblewrap
    - gperf
    - hyphen-devel
    - unifdef
    - xdg-dbus-proxy
rundeps    :
    - bubblewrap
    - xdg-dbus-proxy
setup      : |
    # TODO package libjxl for JPEG XL support
    %cmake_ninja \
                 -DENABLE_DOCUMENTATION=OFF \
                 -DENABLE_GAMEPAD=OFF \
                 -DPORT=GTK \
                 -DUSE_GTK4=ON \
                 -DUSE_JPEGXL=OFF \
                 -DUSE_SOUP2=OFF
build      : |
    # Warning: uses 24G at -j8 with gcc toolchain
    %ninja_build
install    : |
    %ninja_install
