# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : krdp
version    : 6.6.1
release    : 35
source     :
    - https://download.kde.org/stable/plasma/6.6.1/krdp-6.6.1.tar.xz : 67baa1a4af5e30b7ce1b9c70645214a2bf0bf3b8351adca894fb121f597a7553
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Library and examples for creating an RDP server
description: |-
    Library and examples for creating an RDP server
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(freerdp3)
    - pkgconfig(xkbcommon)
    - extra-cmake-modules
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-kstatusnotifieritem-devel
    - kpipewire-devel
    - plasma-wayland-protocols-devel
    - qt6-base-private-devel
    - qtkeychain-qt6-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
