name       : nautilus
version    : '45.0'
release    : 79
source     :
    - https://download.gnome.org/sources/nautilus/45/nautilus-45.0.tar.xz : b311c465ce2ca7bc648f61b865187b4451388dec9358a169f3277e741718ab5d
homepage   : https://wiki.gnome.org/action/show/Apps/Files
license    : GPL-2.0-only
component  :
    - desktop.gnome
    - extension : programming.library
    - extension-devel : programming.devel
summary    : The file manager of the GNOME desktop
description: |
    The file manager of the GNOME desktop
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gi-docgen)
    - pkgconfig(gnome-autoar-0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libadwaita-1)
    - pkgconfig(cloudproviders)
    - pkgconfig(libexif)
    - pkgconfig(libnotify)
    - pkgconfig(libportal-gtk4)
    - pkgconfig(shared-mime-info)
    - pkgconfig(tracker-sparql-3.0)
    - desktop-file-utils
rundeps    :
    - tracker-miners
    - extension-devel :
        - nautilus-extension
    - gvfs
patterns   :
    - /usr/share
    - extension-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
    - extension :
        - /usr/lib64/gi*
        - /usr/lib64/lib*.so.*
replaces   :
    - extension-devel : nautilus-devel
setup      : |
    %apply_patches
    %meson_configure \
        -Ddocs=false \
        -Dpackagekit=false \
        -Dselinux=false
build      : |
    %ninja_build
install    : |
    %ninja_install
