# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : hyprland
version    : 0.54.0
release    : 33
source     :
    - https://github.com/hyprwm/Hyprland/releases/download/v0.54.0/source-v0.54.0.tar.gz : ddc4f7f1dd2d29ebfeaf462fe361593034f104de85b80e3e81f73e33602a69ae
homepage   : https://hyprland.org/
license    : BSD-3-Clause
component  : desktop.hyprland
summary    : Hyprland is a 100% independent, dynamic tiling Wayland compositor that doesn't sacrifice on its looks.
description: |
    Hyprland is a 100% independent, dynamic tiling Wayland compositor that doesn't sacrifice on its looks. It provides the latest Wayland features, is highly customizable, has all the eyecandy, the most powerful plugins, easy IPC, much more QoL stuff than other compositors and more...
builddeps  :
    - pkgconfig(aquamarine)
    - pkgconfig(cairo)
    - pkgconfig(gbm)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gio-2.0)
    - pkgconfig(hwdata)
    - pkgconfig(hyprcursor)
    - pkgconfig(hyprgraphics)
    - pkgconfig(hyprland-protocols)
    - pkgconfig(hyprlang)
    - pkgconfig(hyprutils)
    - pkgconfig(hyprwayland-scanner)
    - pkgconfig(hyprwire)
    - pkgconfig(libdisplay-info)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(libliftoff)
    - pkgconfig(libseat)
    - pkgconfig(libudev)
    - pkgconfig(muparser)
    - pkgconfig(pango)
    - pkgconfig(pangocairo)
    - pkgconfig(pixman-1)
    - pkgconfig(re2)
    - pkgconfig(tomlplusplus)
    - pkgconfig(uuid)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-cursor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-errors)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-util)
    - pkgconfig(xcursor)
    - pkgconfig(xkbcommon)
    - pkgconfig(xwayland)
    - glaze
rundeps    :
    - hyprland-guiutils
    - xdg-desktop-portal-gtk
    - xdg-desktop-portal-hyprland
setup      : |
    rm -rf subprojects/hyprland-protocols
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %install_license LICENSE
