name       : gmime
version    : 3.2.14
release    : 22
source     :
    - https://github.com/jstedfast/gmime/releases/download/3.2.14/gmime-3.2.14.tar.xz : a5eb3dd675f72e545c8bc1cd12107e4aad2eaec1905eb7b4013cdb1fbe5e2317
homepage   : https://github.com/jstedfast/gmime
license    : LGPL-2.1-only
component  : programming.library
summary    : MIME parsing/creation library
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
builddeps  :
    - pkgconfig(gpgme)
    - pkgconfig(libassuan)
    - vala
setup      : |
    %configure --enable-crypto --disable-static
build      : |
    %make
install    : |
    %make_install
