name       : libpanel
version    : 1.4.0
release    : 4
source     :
    - https://download.gnome.org/sources/libpanel/1.4/libpanel-1.4.0.tar.xz : 80f143d900e8ced8ff84fa86fe34eb6b48323cb610bcfb6858ea65d8b98f152c
homepage   : https://gitlab.gnome.org/GNOME/libpanel
license    : LGPL-2.1-or-later
component  : programming.library
summary    : A dock/panel library for GTK 4
description: |
    Libpanel helps you create IDE-like applications using GTK 4 and libadwaita. It has widgets for panels, docks, columns and grids of pages. Primarily, it's design and implementation focus around GNOME Builder and Drafting projects.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - vala
setup      : |
    %meson_configure -Ddocs=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
