# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : deno
version    : 2.7.1
release    : 37
source     :
    - https://github.com/denoland/deno/archive/refs/tags/v2.7.1.tar.gz : 07b03b81c5e7d393c2a4897ff8258f03a4d95efe99b48d5af4244e490ddd043b
homepage   : https://deno.com/
license    : MIT
component  : programming.tools
summary    : A modern runtime for JavaScript and TypeScript
description: |
    Deno is a JavaScript, TypeScript, and WebAssembly runtime with secure defaults and a great developer experience. It's built on V8, Rust, and Tokio.
networking : true
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install

    # Generate completions
    install -dm00644 $installdir/usr/share/bash-completion/completions
    install -dm00644 $installdir/usr/share/zsh/site-functions
    install -dm00644 $installdir/usr/share/fish/vendor_completions.d
    ./target/release/deno completions bash > $installdir/usr/share/bash-completion/completions/deno
    ./target/release/deno completions zsh  > $installdir/usr/share/zsh/site-functions/_deno
    ./target/release/deno completions fish > $installdir/usr/share/fish/vendor_completions.d/deno.fish
