# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-vault
version    : 6.6.1
release    : 106
source     :
    - https://download.kde.org/stable/plasma/6.6.1/plasma-vault-6.6.1.tar.xz : 7c04cb60cfea937c1a8f9b39c588136b50c57b75f22c06ebf8bfba2d25dc19d0
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(libnm)
    - kf6-kdbusaddons-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma-activities-devel
rundeps    :
    - cryfs
    - gocryptfs
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
