name       : libei
version    : 1.1.0
release    : 1
source     :
    - https://gitlab.freedesktop.org/libinput/libei/-/archive/1.1.0/libei-1.1.0.tar.gz : 23a6890ba1139249f5c9f6d33ce6be2ad04bd0236f339eeb62c7460cbd4932de
homepage   : https://libinput.pages.freedesktop.org/libei/
license    : MIT
component  : desktop.library
summary    : libei is a library for Emulated Input, primarily aimed at the Wayland stack. 
description: |
    libei is a library for Emulated Input, primarily aimed at the Wayland stack.
builddeps  :
    - pkgconfig(libevdev)
    - pkgconfig(xkbcommon)
    - python-attrs
    - python-jinja
setup      : |
    %meson_configure -Dtests=disabled
build      : |
    %ninja_build
install    : |
    %ninja_install
