# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : highlight
version    : '4.19'
release    : 22
source     :
    - https://gitlab.com/saalen/highlight/-/archive/v4.19/highlight-v4.19.tar.gz : 0f243a9fb72da88148db473c9411c92c4988bf940bff32eef939bc1efa0017c8
homepage   : https://gitlab.com/saalen/highlight
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Convert source code to formatted text with syntax highlighting
description: |
    Highlight converts source code to HTML, XHTML, RTF, LaTex, TeX, SVG, BBCode and terminal escape sequences with coloured syntax highlighting. Language definitions and colour themes are customizable.
builddeps  :
    - pkgconfig(lua-5.4)
    - libboost-devel
build      : |
    %make
install    : |
    %make_install
    %install_license COPYING

    # remove documentation files
    rm -r $installdir/usr/share/doc
