name       : libshumate
version    : 1.1.0
release    : 4
source     :
    - https://download.gnome.org/sources/libshumate/1.1/libshumate-1.1.0.tar.xz : b3b7c4c2d3002f37b951c9ca99b09275d0aa82265c69f53374ce12faefd3b14e
homepage   : https://wiki.gnome.org/Projects/libshumate
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Shumate is a GTK toolkit providing widgets for embedded maps.
description: |
    Shumate is a GTK toolkit providing widgets for embedded maps.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk4)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(sqlite3)
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
