# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : freeciv
version    : 3.2.2
release    : 46
source     :
    - https://files.freeciv.org/stable/freeciv-3.2.2.tar.xz : ed230084e885d19d82170a8b39e43e3291ec446c37239bf2bee8e11245c88960
license    : GPL-2.0-or-later
homepage   : https://www.freeciv.org/
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : false
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(Qt6Core)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(gtk4)
    - pkgconfig(libcurl)
    - pkgconfig(lua-5.4)
    - pkgconfig(sqlite3)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
