name       : python-jupyter-server-terminals
version    : 0.4.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter_server_terminals/jupyter_server_terminals-0.4.4.tar.gz : 57ab779797c25a7ba68e97bcfb5d7740f2b5e8a83b5e8102b10438041a7eac5d
homepage   : https://github.com/jupyter-server/jupyter_server_terminals
license    : BSD-3-Clause
component  : programming.python
summary    : A Jupyter Server Extension Providing Terminals
description: |
    Jupyter Server Terminals is a Jupyter Server Extension providing support for terminals.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-terminado
build      : |
    %python3_setup
install    : |
    %python3_install
