name       : python-nbclassic
version    : 1.0.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/n/nbclassic/nbclassic-1.0.0.tar.gz : 0ae11eb2319455d805596bf320336cda9554b41d99ab9a3c31bf8180bffa30e3
homepage   : https://github.com/jupyter/nbclassic
license    : BSD-3-Clause
component  : programming.python
summary    : A web-based notebook environment for interactive computing
description: |
    The Jupyter NbClassic is a web application that allows you to create and share documents that contain live code, equations, visualizations, and explanatory text. The NbClassic has support for multiple programming languages, sharing, and interactive widgets.
rundeps    :
    - python-ipykernel
    - python-ipython_genutils
    - python-jupyter-server
    - python-notebook-shim
build      : |
    %python3_setup
install    : |
    %python3_install
