name       : libgtop
version    : 2.41.2
release    : 21
source     :
    - https://download.gnome.org/sources/libgtop/2.41/libgtop-2.41.2.tar.xz : d9026cd8a48d27cdffd332f8d60a92764b56424e522c420cd13a01f40daf92c3
homepage   : https://gitlab.gnome.org/GNOME/libgtop
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : GNOME top libraries
description: |
    The libgtop package contains the GNOME top libraries.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
