# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kdiff3
version    : 1.12.3
release    : 5
source     :
    - https://download.kde.org/stable/kdiff3/kdiff3-1.12.3.tar.xz : e22654c457881799808305529c6b596c0c9dc38b5a2ecc142ec76d46f6873f4c
license    : GPL-2.0-or-later
component  : programming.tools
homepage   : https://apps.kde.org/kdiff3
summary    : Utility for comparing and merging files and directories
description: |
    kdiff3 is a 3-way text editor from KDE capable of comparing and merging two or three input files or directories. It is a supported git mergetool.
optimize   :
    - lto
builddeps  :
    - pkgconfig(Qt6Gui)
    - pkgconfig(cups)
    - kf6-kconfig
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
