# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : wayland-utils
version    : 1.3.0
release    : 3
source     :
    - https://gitlab.freedesktop.org/wayland/wayland-utils/-/archive/1.3.0/wayland-utils-1.3.0.tar.gz : e55863922d72a219546c3967080d645782d263f8449faea6c3e3ce961fa35b32
homepage   : https://gitlab.freedesktop.org/wayland/wayland-utils
license    :
    - X11
    - MIT
component  : system.utils
summary    : wayland-info is a utility for displaying information about the Wayland protocols supported by a Wayland compositor.
description: |
    wayland-info is a utility for displaying information about the Wayland protocols supported by a Wayland compositor. It can be used to check which Wayland protocols and versions are advertised by the Wayland compositor. wayland-info also provides additional information for a subset of Wayland protocols it knows about, namely Linux DMABUF, presentation time, tablet and XDG output protocols.
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
