name       : yarn
version    : 1.22.19
release    : 59
source     :
    - https://registry.npmjs.org/yarn/-/yarn-1.22.19.tgz#yarn.tgz : 732620bac8b1690d507274f025f3c6cfdc3627a84d9642e38a07452cc00e0f2e
license    : BSD-2-Clause
component  : programming.tools
extract    : no
homepage   : https://classic.yarnpkg.com/
summary    : Fast, reliable, and secure dependency management for JavaScript.
description: |
    Fast, reliable, and secure dependency management for JavaScript.
builddeps  :
    - nodejs
rundeps    :
    - nodejs
install    : |
    npm install -g --prefix "$installdir/usr" $sources/yarn.tgz
