# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : kactivitymanagerd
version    : 6.6.1
release    : 132
source     :
    - https://download.kde.org/stable/plasma/6.6.1/kactivitymanagerd-6.6.1.tar.xz : bef68b4bbeb36b0da8f3b5b5931d7bec5a7f57fc89ea21f46ea099ca2fc14705
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : false
builddeps  :
    - kf6-kcrash-devel
    - kf6-kglobalaccel-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libboost-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
