# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : wireless-regdb
version    : 2026.02.04
release    : 10
source     :
    - https://mirrors.edge.kernel.org/pub/software/network/wireless-regdb/wireless-regdb-2026.02.04.tar.gz : d7b4bcc83e9c136a241b20249582ddbd44556bd9c2f856818602269c73fe0185
homepage   : https://wireless.wiki.kernel.org/en/developers/regulatory/wireless-regdb
license    : ISC
component  : system.base
summary    : This package contains the wireless regulatory database used by all cfg80211 based Linux wireless drivers.
description: |
    This package contains the wireless regulatory database used by all cfg80211 based Linux wireless drivers.
install    : |
    %make_install FIRMWARE_PATH=/usr/lib64/firmware

    # Usr-merge
    install -dm00755 $installdir/lib64
    pushd $installdir/usr
    file_list=()
    while IFS=  read -r -d $'\0'; do
        file_list+=("$REPLY")
    done < <(find lib64 -type f -print0)
    for file in "${file_list[@]}"; do
        parent=$(dirname "$file")
        install -dm00755 "$installdir/$parent"
        ln -srv "$installdir/usr/$file" "$installdir/$file"
    done
    popd
