name       : python-rpds-py
version    : 0.10.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/r/rpds_py/rpds_py-0.10.4.tar.gz : 18d5ff7fbd305a1d564273e9eb22de83ae3cd9cd6329fddc8f12f6428a711a6a
homepage   : https://github.com/crate-py/rpds
license    : MIT
component  : programming.python
summary    : Python bindings to Rust's persistent data structures (rpds)
description: |
    Python bindings to the Rust rpds crate for persistent data structures.
networking : yes
builddeps  :
    - cargo
    - python-build
    - python-installer
    - python-maturin
build      : |
    %python3_setup
install    : |
    %python3_install
