name       : gnome-weather
version    : '45.0'
release    : 27
source     :
    - https://download.gnome.org/sources/gnome-weather/45/gnome-weather-45.0.tar.xz : 30c0029702883dc8d8160e6de1d6116877cd6c25bc950d4e4902a6ab467b2fa4
homepage   : https://wiki.gnome.org/Apps/Weather
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgeoclue-2.0)
    - desktop-file-utils
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
