name       : libgtksourceview5
version    : 5.10.0
release    : 5
source     :
    - https://download.gnome.org/sources/gtksourceview/5.10/gtksourceview-5.10.0.tar.xz : b38a3010c34f59e13b05175e9d20ca02a3110443fec2b1e5747413801bc9c23f
homepage   : https://wiki.gnome.org/Projects/GtkSourceView
license    : LGPL-2.1
component  : desktop.gnome.core
summary    : A text widget adding syntax highlighting and more to GNOME
description: |
    A text widget adding syntax highlighting and more to GNOME
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libpcre2-posix)
    - valadoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
