name       : xdg-desktop-portal
version    : 1.18.0
release    : 25
source     :
    - https://github.com/flatpak/xdg-desktop-portal/releases/download/1.18.0/xdg-desktop-portal-1.18.0.tar.xz : 5ea35a6420a98b598c83355fc19feaea8ba999149641bf84079b0c572b00f5bd
homepage   : https://github.com/flatpak/xdg-desktop-portal
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : Desktop integration portal
description: |
    A portal frontend service for Flatpak and possibly other desktop containment frameworks. xdg-desktop-portal works by exposing a series of D-Bus interfaces known as portals under a well-known name (org.freedesktop.portal.Desktop) and object path (/org/freedesktop/portal/desktop). The portal interfaces include APIs for file access, opening URIs, printing and others.
builddeps  :
    - pkgconfig(flatpak)
    - pkgconfig(fontconfig)
    - pkgconfig(fuse3)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libportal)
    - docbook-xml
    - xmlto
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
