name       : python-mistune
version    : 3.0.2
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/m/mistune/mistune-3.0.2.tar.gz : fc7f93ded930c92394ef2cb6f04a8aabab4117a91449e72dcc8dfa646a508be8
homepage   : https://github.com/lepture/mistune
license    : BSD-3-Clause
component  : programming.python
summary    : A sane Markdown parser with useful plugins and renderers
description: |
    A fast yet powerful Python Markdown parser with renderers and plugins.
builddeps  :
    - cython
    - python-build
    - python-installer
    - python-packaging
    - python-pytest
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
