name       : clutter-gst
version    : 3.0.27
release    : 23
source     :
    - https://download.gnome.org/sources/clutter-gst/3.0/clutter-gst-3.0.27.tar.xz : fe69bd6c659d24ab30da3f091eb91cd1970026d431179b0724f13791e8ad9f9d
homepage   : https://gitlab.gnome.org/GNOME/clutter-gst
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Clutter GStreamer API
description: |
    Clutter GStreamer API
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(cogl-2.0-experimental)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - gtk-doc
setup      : |
    %patch -p1 -i $pkgfiles/0001-video-sink-Remove-RGBx-BGRx-support.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
