# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ksshaskpass
version    : 6.6.1
release    : 133
source     :
    - https://download.kde.org/stable/plasma/6.6.1/ksshaskpass-6.6.1.tar.xz : 39d9639d6c3cc68aceaa403ed5bee8da0efab17cd3452cdb2f6fef25b2666787
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kwallet-devel
    - kf6-kwidgetsaddons-devel
    - qt6-base-private-devel
    - qtkeychain-qt6-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
