name       : rymdport
version    : 3.5.1
release    : 8
source     :
    - https://github.com/Jacalz/rymdport/releases/download/v3.5.1/rymdport-v3.5.1-vendored.tar.xz : 08495b45f2898b9d1da570e684e2c8e048fb8a72fd9562393a692eb128961213
license    : GPL-3.0-or-later
homepage   : https://github.com/Jacalz/rymdport
component  : network.clients
summary    : Easy encrypted file, folder, and text sharing between devices.
description: |
    Rymdport (formerly wormhole-gui) is a cross-platform application that lets you easily and safely share files, folders, and text between devices. The data is sent securely with end-to-end encryption using the same protocol as magic-wormhole. This means that Rymdport can talk not only to itself, but also to other wormhole clients.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
    - golang
build      : |
    go build -tags no_emoji -trimpath -ldflags="-s -w" -buildvcs=false -o rymdport
install    : |
    %make_install
