name       : libcloudproviders
version    : 0.3.4
release    : 10
source     :
    - https://download.gnome.org/sources/libcloudproviders/0.3/libcloudproviders-0.3.4.tar.xz : e3d7160c3e45fe3216c07c7988bb4fc81397c32d1fc6113af0edfe8632039f65
homepage   : https://gitlab.gnome.org/World/libcloudproviders
license    : LGPL-3.0-or-later
component  : programming.library
summary    : libcloudproviders is a DBus API that allows cloud storage sync clients to expose their services.
description: |
    libcloudproviders is a DBus API that allows cloud storage sync clients to expose their services. Clients such as file managers and desktop environments can then provide integrated access to the cloud providers services.
builddeps  :
    - pkgconfig(glib-2.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
