# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : libksysguard
version    : 6.6.1
release    : 135
source     :
    - https://download.kde.org/stable/plasma/6.6.1/libksysguard-6.6.1.tar.xz : 633db72922d2c7f8a86e533cedec2695212e61981a885f1df07c2eeb72f4312c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
builddeps  :
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libpcap)
    - pkgconfig(xres)
    - kf6-kauth-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - lm_sensors-devel
    - qt6-base-private-devel
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
