# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xkill
version    : 1.0.7
release    : 12
source     :
    - https://www.x.org/releases/individual/app/xkill-1.0.7.tar.gz : aec5674d48d1749742e87dfbff30f1abacabe5e2a10c0679c3996882444c9f6d
license    : MIT
component  : xorg.apps
homepage   : https://www.x.org/
summary    : |
    X.Org Applications: xkill
description: |
    xkill is a utility for forcing the X server to close connections to clients
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xmuu)
    - pkgconfig(xorg-macros)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
