name       : orca
version    : '45.1'
release    : 26
source     :
    - https://download.gnome.org/sources/orca/45/orca-45.1.tar.xz : bfcc06bf4bc47bbd02c1568d1e464bf16a31e62bf703b49aa13b08db38a1a8ca
homepage   : https://gitlab.gnome.org/GNOME/orca
license    : LGPL-2.1-or-later
component  : desktop.gnome
summary    : Orca Screen Reader
description: |
    Orca is a free, open source, flexible, and extensible screen reader that provides access to the graphical desktop via user-customizable combinations of speech and/or braille.
builddeps  :
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
    - pkgconfig(speech-dispatcher)
    - itstool
    - yelp-tools
rundeps    :
    - pyatspi2
    - speech-dispatcher
setup      : |
    %patch -p1 -i $pkgfiles/0001-Tweak-configure.ac.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
