# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : plasma-thunderbolt
version    : 6.6.1
release    : 94
source     :
    - https://download.kde.org/stable/plasma/6.6.1/plasma-thunderbolt-6.6.1.tar.xz : 561033a11268d219ffea8dcaf4b7476232d459e302f5a4e59523355004882d81
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma integration for controlling Thunderbolt devices
description: |-
    Plasma integration for controlling Thunderbolt devices
libsplit   : false
builddeps  :
    - bolt
    - kf6-kcmutils-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-knotifications-devel
rundeps    :
    - bolt
clang      : true
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
