name       : minizip-ng
version    : 4.0.1
release    : 2
source     :
    - https://github.com/zlib-ng/minizip-ng/archive/refs/tags/4.0.1.tar.gz#minizip-ng.tar.gz : 63e47a2b4dbac0da501f43f4da74f118dfb3ef0dee0ffbbe89428271002260f8
license    : Zlib
homepage   : https://github.com/zlib-ng/minizip-ng
component  : system.utils
summary    : Fork of the zlib zip library
description: |
    Fork of the popular zip manipulation library found in the zlib distribution
clang      : yes
extract    : no
optimize   :
    - speed
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(libcrypto)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
replaces   :
    - zlib-minizip
    - devel : zlib-minizip-devel
setup      : |
    for i in compat regular; do
        if [ $i == 'compat' ]; then
            obsolete=ON
        else
            obsolete=OFF
        fi

        mkdir $i
        tar -xf $sources/minizip-ng.tar.gz -C $i --strip-components 1
        pushd $i

        %cmake_ninja \
                     -DBUILD_SHARED_LIBS=ON \
                     -DMZ_LIBBSD=OFF \
                     -DMZ_COMPAT=$obsolete
        popd
    done
build      : |
    for i in compat regular; do
        pushd $i
        %ninja_build
        popd
    done
install    : |
    for i in compat regular; do
        pushd $i
        %ninja_install
        popd
    done
# TODO Split the compat library out to a different package.
