name       : minizip-ng
version    : 4.0.1
release    : 1
source     :
    - https://github.com/zlib-ng/minizip-ng/archive/refs/tags/4.0.1.tar.gz : 63e47a2b4dbac0da501f43f4da74f118dfb3ef0dee0ffbbe89428271002260f8
license    : Zlib
homepage   : https://github.com/zlib-ng/minizip-ng
component  : system.utils
summary    : Fork of the zlib zip library
description: |
    Fork of the popular zip manipulation library found in the zlib distribution
clang      : yes
optimize   :
    - speed
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(libcrypto)
    - pkgconfig(liblzma)
    - pkgconfig(libzstd)
replaces   :
    - zlib-minizip
    - devel : zlib-minizip-devel
setup      : |
    %cmake_ninja \
                 -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
