name       : harfbuzz
version    : 8.2.1
release    : 65
source     :
    - https://github.com/harfbuzz/harfbuzz/releases/download/8.2.1/harfbuzz-8.2.1.tar.xz : 0fec78f98c9c8faf228957a201c8846f809452c20f8445eb092a1ba6f22dbea5
license    :
    - MIT
    - HPND
homepage   : https://www.freedesktop.org/wiki/Software/HarfBuzz
component  : xorg.fonts
summary    : HarfBuzz is a text shaping library
description: |
    HarfBuzz is a software development library for text shaping, which is the process of converting Unicode text to glyph indices and positions.
emul32     : yes
optimize   : lto
autodep    : no
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(graphite2)
    - pkgconfig32(icu-io)
rundeps    :
    - glib2
    - glibc
    - graphite2
    - libicu
    - 32bit :
        - glib2-32bit
        - glibc-32bit
        - graphite2-32bit
        - harfbuzz
        - libgcc-32bit
    - 32bit-devel :
        - glib2-32bit-devel
        - graphite2-32bit-devel
        - harfbuzz-devel
        - libicu-32bit-devel
    - devel :
        - glib2-devel
        - graphite2-devel
        - libicu-devel
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi

    %meson_configure -Dbenchmark=disabled -Dgraphite=enabled -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
