name       : ansible
version    : 2.15.5
release    : 41
source     :
    - https://github.com/ansible/ansible/archive/refs/tags/v2.15.5.tar.gz : f56be7cde9dcf7e7ce881cac013efaa2e15c768d85547031ca148ed76f1f8b2d
license    : GPL-3.0-or-later
homepage   : https://www.ansible.com/
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-docutils
    - python-jinja
rundeps    :
    - python-jinja
    - python-paramiko
    - python-resolvelib
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
