name       : gnome-sudoku
version    : '45.1'
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-sudoku/45/gnome-sudoku-45.1.tar.xz : fb5437961a33d2ab7ad3081648e5df6b193a1b86224213ef23b973914a9f7c90
homepage   : https://wiki.gnome.org/Apps/Sudoku/
license    : GPL-3.0-or-later
component  : games.puzzle
summary    : Sudoku - The popular Japanese logic puzzle
description: |
    Sudoku is a Japanese logic game that exploded in popularity in 2005. This is a logic-based number-placement puzzle in which a 9×9 square must be filled with the correct digits.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(qqwing)
    - desktop-file-utils
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
