# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : appstream-catalog
version    : '20260227'
release    : 45
source     :
    - https://appstream.getsol.us/data/unstable/main/Components-x86_64.xml.gz: ff9cf9c33eb04936ba0e7b626efeafbd59b7ec695b8417e620a1e9d904512b24
    - https://appstream.getsol.us/data/unstable/main/icons-128x128.tar.gz: 6985a21f2038f5d5da208f0a2dc8751d8a5b0529d2dde6062c8ed809b8d5574b
    - https://appstream.getsol.us/data/unstable/main/icons-128x128@2.tar.gz: c6c39a9236603f38b79f59086f003fc0f323393a549d20d1bf5f37e04010ce17
    - https://appstream.getsol.us/data/unstable/main/icons-48x48.tar.gz: 05a611f4205481eeaa90efa41cb11e24bce311e51334b54fe202d9dfd24def98
    - https://appstream.getsol.us/data/unstable/main/icons-48x48@2.tar.gz: 670597dfe0f326bd1c1eb6316f1da918a819221abc6397ceaa43ab36943a9d57
    - https://appstream.getsol.us/data/unstable/main/icons-64x64.tar.gz: f3ee14ccf88b39f34efeac154163de3fd7ab14c9d60304ba81e2b62223025996
    - https://appstream.getsol.us/data/unstable/main/icons-64x64@2.tar.gz: 6efcd432515b980842edecd471ae080f5eaeaf5349d606c820bf308ca3325c7d
homepage   : https://www.freedesktop.org/wiki/Distributions/AppStream/
license    :
    - CC-BY-SA-3.0
    - CC-BY-SA-4.0
    - CC0-1.0
    - GFDL-1.3
component  : desktop.core
summary    : AppStream data for Solus
description: |
    AppStream data for Solus
extract    : false
install    : |
    install -Dm00644 $sources/Components-x86_64.xml.gz $installdir/usr/share/swcatalog/xml/solus-unstable-main.xml.gz

    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    install -dm00644 $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2

    tar xf $sources/icons-48x48.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48
    tar xf $sources/icons-48x48@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/48x48@2
    tar xf $sources/icons-64x64.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64
    tar xf $sources/icons-64x64@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/64x64@2
    tar xf $sources/icons-128x128.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128
    tar xf $sources/icons-128x128@2.tar.gz -C $installdir/usr/share/swcatalog/icons/solus-unstable-main/128x128@2
replaces   : appstream-data
