name       : libavif
version    : 1.0.1
release    : 14
source     :
    - https://github.com/AOMediaCodec/libavif/archive/refs/tags/v1.0.1.tar.gz : 398fe7039ce35db80fe7da8d116035924f2c02ea4a4aa9f4903df6699287599c
license    : BSD-2-Clause
component  : multimedia.library
homepage   : https://github.com/AOMediaCodec/libavif
summary    : Library for encoding and decoding .avif files
description: |
    libavif aims to be a friendly and portable C implementation of the AV1 Image File Format, capable of both encoding and decoding.
builddeps  :
    - pkgconfig(SvtAv1Enc)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libsharpyuv)
    - pkgconfig(rav1e)
    - gtest-devel
setup      : |
    %cmake_ninja \
                 -DAVIF_BUILD_APPS=ON \
                 -DAVIF_BUILD_TESTS=ON \
                 -DAVIF_CODEC_AOM=ON \
                 -DAVIF_CODEC_DAV1D=ON \
                 -DAVIF_CODEC_RAV1E=ON \
                 -DAVIF_CODEC_SVT=ON \
                 -DAVIF_BUILD_GDK_PIXBUF=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
