# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : freepats
version    : 1.0.3
release    : 4
source     :
    - https://github.com/feross/freepats/archive/v1.0.3.tar.gz : d79fa8719500880627b1b65286fde6ddb06274540a3eba21178d2058d525007e
homepage   : https://github.com/feross/freepats/
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Old FreePats General MIDI sound set
description: |
    Old version of FreePats General MIDI sound set, initially put together by Eric A. Welsh more than 12 years ago.
install    : |
    install -dm00644 $installdir/usr/share/soundfonts/freepats/Drum_000
    install -m00644 Drum_000/*.pat $installdir/usr/share/soundfonts/freepats/Drum_000/

    install -dm00644 $installdir/usr/share/soundfonts/freepats/Tone_000
    install -m00644 Tone_000/*.pat $installdir/usr/share/soundfonts/freepats/Tone_000/

    sed -i 's|Drum_000|/usr/share/soundfonts/freepats/Drum_000|g' freepats.cfg
    sed -i 's|Tone_000|/usr/share/soundfonts/freepats/Tone_000|g' freepats.cfg
    install -Dm00644 freepats.cfg $installdir/etc/timidity/freepats.cfg
