# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : ccid
version    : 1.7.1
release    : 15
source     :
    - https://ccid.apdu.fr/files/ccid-1.7.1.tar.xz : 32799ab16fe6e493c9452be3823f21810fbe80b884021a6f6f3fa69f26be5c86
homepage   : https://ccid.apdu.fr/
license    : LGPL-2.1-or-later
component  : programming
summary    : Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver
description: |
    Generic USB CCID (Chip/Smart Card Interface Devices) and ICCD (Integrated Circuit(s) Card Devices) driver.
builddeps  :
    - pkgconfig(libpcsclite)
    - pkgconfig(libusb-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 src/92_pcscd_ccid.rules $installdir/%libdir%/udev/rules.d/92_pcscd_ccid.rules
