# yaml-language-server: $schema=/usr/share/ypkg/schema/schema.json
name       : xwayland-run
version    : 0.0.5
release    : 6
source     :
    - https://gitlab.freedesktop.org/ofourdan/xwayland-run/-/archive/0.0.5/xwayland-run-0.0.5.tar.gz : b000386a0f0270cf49d5207b60215de7a09423d8afe3a45fe3e315791667fbb5
homepage   : https://gitlab.freedesktop.org/ofourdan/xwayland-run
license    : GPL-2.0-or-later
component  : system.utils
summary    : xwayland-run contains a set of small utilities revolving around running Xwayland and various Wayland compositor headless.
description: |
    xwayland-run contains a set of small utilities revolving around running Xwayland and various Wayland compositor headless.
    It provides:
     - xwayland-run, to spawn an X11 client within its own dedicated Xwayland rootful instance,
     - wlheadless-run to run a Wayland client on a set of supported Wayland headless compositors, and
     - xwfb-run, a combination of the two other tools above to be used as a direct replacement for xvfb-run specifically.
rundeps    :
    - weston # default compositor
    - xorg-xwayland
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
